/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DashboardUploadsRouteImport } from './routes/_dashboard/uploads'
import { Route as DashboardUnmappedRcRouteImport } from './routes/_dashboard/unmapped-rc'
import { Route as DashboardTransactionsRouteImport } from './routes/_dashboard/transactions'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardGeneratorRouteImport } from './routes/_dashboard/generator'
import { Route as DashboardDictionaryRouteImport } from './routes/_dashboard/dictionary'
import { Route as DashboardApplicationRouteImport } from './routes/_dashboard/application'
import { Route as DashboardSuperadminIndexRouteImport } from './routes/_dashboard/superadmin/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardSuperadminUsersRouteImport } from './routes/_dashboard/superadmin/users'
import { Route as DashboardSuperadminJobsRouteImport } from './routes/_dashboard/superadmin/jobs'
import { Route as DashboardSuperadminIndexAnalyzerRouteImport } from './routes/_dashboard/superadmin/index-analyzer'
import { Route as DashboardSuperadminHousekeepingRouteImport } from './routes/_dashboard/superadmin/housekeeping'
import { Route as DashboardSuperadminDatabasesRouteImport } from './routes/_dashboard/superadmin/databases'
import { Route as DashboardSuperadminAuditLogsRouteImport } from './routes/_dashboard/superadmin/audit-logs'
import { Route as DashboardSuperadminApplicationAppIdRouteImport } from './routes/_dashboard/superadmin/application.$appId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUploadsRoute = DashboardUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUnmappedRcRoute = DashboardUnmappedRcRouteImport.update({
  id: '/unmapped-rc',
  path: '/unmapped-rc',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGeneratorRoute = DashboardGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDictionaryRoute = DashboardDictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationRoute = DashboardApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuperadminIndexRoute =
  DashboardSuperadminIndexRouteImport.update({
    id: '/superadmin/',
    path: '/superadmin/',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSuperadminUsersRoute =
  DashboardSuperadminUsersRouteImport.update({
    id: '/superadmin/users',
    path: '/superadmin/users',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuperadminJobsRoute = DashboardSuperadminJobsRouteImport.update({
  id: '/superadmin/jobs',
  path: '/superadmin/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuperadminIndexAnalyzerRoute =
  DashboardSuperadminIndexAnalyzerRouteImport.update({
    id: '/superadmin/index-analyzer',
    path: '/superadmin/index-analyzer',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuperadminHousekeepingRoute =
  DashboardSuperadminHousekeepingRouteImport.update({
    id: '/superadmin/housekeeping',
    path: '/superadmin/housekeeping',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuperadminDatabasesRoute =
  DashboardSuperadminDatabasesRouteImport.update({
    id: '/superadmin/databases',
    path: '/superadmin/databases',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuperadminAuditLogsRoute =
  DashboardSuperadminAuditLogsRouteImport.update({
    id: '/superadmin/audit-logs',
    path: '/superadmin/audit-logs',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuperadminApplicationAppIdRoute =
  DashboardSuperadminApplicationAppIdRouteImport.update({
    id: '/superadmin/application/$appId',
    path: '/superadmin/application/$appId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/application': typeof DashboardApplicationRoute
  '/dictionary': typeof DashboardDictionaryRoute
  '/generator': typeof DashboardGeneratorRoute
  '/settings': typeof DashboardSettingsRoute
  '/transactions': typeof DashboardTransactionsRoute
  '/unmapped-rc': typeof DashboardUnmappedRcRoute
  '/uploads': typeof DashboardUploadsRoute
  '/api/health': typeof ApiHealthRoute
  '/superadmin/audit-logs': typeof DashboardSuperadminAuditLogsRoute
  '/superadmin/databases': typeof DashboardSuperadminDatabasesRoute
  '/superadmin/housekeeping': typeof DashboardSuperadminHousekeepingRoute
  '/superadmin/index-analyzer': typeof DashboardSuperadminIndexAnalyzerRoute
  '/superadmin/jobs': typeof DashboardSuperadminJobsRoute
  '/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/superadmin/': typeof DashboardSuperadminIndexRoute
  '/superadmin/application/$appId': typeof DashboardSuperadminApplicationAppIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/application': typeof DashboardApplicationRoute
  '/dictionary': typeof DashboardDictionaryRoute
  '/generator': typeof DashboardGeneratorRoute
  '/settings': typeof DashboardSettingsRoute
  '/transactions': typeof DashboardTransactionsRoute
  '/unmapped-rc': typeof DashboardUnmappedRcRoute
  '/uploads': typeof DashboardUploadsRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof DashboardIndexRoute
  '/superadmin/audit-logs': typeof DashboardSuperadminAuditLogsRoute
  '/superadmin/databases': typeof DashboardSuperadminDatabasesRoute
  '/superadmin/housekeeping': typeof DashboardSuperadminHousekeepingRoute
  '/superadmin/index-analyzer': typeof DashboardSuperadminIndexAnalyzerRoute
  '/superadmin/jobs': typeof DashboardSuperadminJobsRoute
  '/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/superadmin': typeof DashboardSuperadminIndexRoute
  '/superadmin/application/$appId': typeof DashboardSuperadminApplicationAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_dashboard/application': typeof DashboardApplicationRoute
  '/_dashboard/dictionary': typeof DashboardDictionaryRoute
  '/_dashboard/generator': typeof DashboardGeneratorRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/transactions': typeof DashboardTransactionsRoute
  '/_dashboard/unmapped-rc': typeof DashboardUnmappedRcRoute
  '/_dashboard/uploads': typeof DashboardUploadsRoute
  '/api/health': typeof ApiHealthRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/superadmin/audit-logs': typeof DashboardSuperadminAuditLogsRoute
  '/_dashboard/superadmin/databases': typeof DashboardSuperadminDatabasesRoute
  '/_dashboard/superadmin/housekeeping': typeof DashboardSuperadminHousekeepingRoute
  '/_dashboard/superadmin/index-analyzer': typeof DashboardSuperadminIndexAnalyzerRoute
  '/_dashboard/superadmin/jobs': typeof DashboardSuperadminJobsRoute
  '/_dashboard/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_dashboard/superadmin/': typeof DashboardSuperadminIndexRoute
  '/_dashboard/superadmin/application/$appId': typeof DashboardSuperadminApplicationAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/application'
    | '/dictionary'
    | '/generator'
    | '/settings'
    | '/transactions'
    | '/unmapped-rc'
    | '/uploads'
    | '/api/health'
    | '/superadmin/audit-logs'
    | '/superadmin/databases'
    | '/superadmin/housekeeping'
    | '/superadmin/index-analyzer'
    | '/superadmin/jobs'
    | '/superadmin/users'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/superadmin/'
    | '/superadmin/application/$appId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/application'
    | '/dictionary'
    | '/generator'
    | '/settings'
    | '/transactions'
    | '/unmapped-rc'
    | '/uploads'
    | '/api/health'
    | '/'
    | '/superadmin/audit-logs'
    | '/superadmin/databases'
    | '/superadmin/housekeeping'
    | '/superadmin/index-analyzer'
    | '/superadmin/jobs'
    | '/superadmin/users'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/superadmin'
    | '/superadmin/application/$appId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/register'
    | '/_dashboard/application'
    | '/_dashboard/dictionary'
    | '/_dashboard/generator'
    | '/_dashboard/settings'
    | '/_dashboard/transactions'
    | '/_dashboard/unmapped-rc'
    | '/_dashboard/uploads'
    | '/api/health'
    | '/_dashboard/'
    | '/_dashboard/superadmin/audit-logs'
    | '/_dashboard/superadmin/databases'
    | '/_dashboard/superadmin/housekeeping'
    | '/_dashboard/superadmin/index-analyzer'
    | '/_dashboard/superadmin/jobs'
    | '/_dashboard/superadmin/users'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_dashboard/superadmin/'
    | '/_dashboard/superadmin/application/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/uploads': {
      id: '/_dashboard/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof DashboardUploadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/unmapped-rc': {
      id: '/_dashboard/unmapped-rc'
      path: '/unmapped-rc'
      fullPath: '/unmapped-rc'
      preLoaderRoute: typeof DashboardUnmappedRcRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/transactions': {
      id: '/_dashboard/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/generator': {
      id: '/_dashboard/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof DashboardGeneratorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dictionary': {
      id: '/_dashboard/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DashboardDictionaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/application': {
      id: '/_dashboard/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof DashboardApplicationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/': {
      id: '/_dashboard/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof DashboardSuperadminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/superadmin/users': {
      id: '/_dashboard/superadmin/users'
      path: '/superadmin/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof DashboardSuperadminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/jobs': {
      id: '/_dashboard/superadmin/jobs'
      path: '/superadmin/jobs'
      fullPath: '/superadmin/jobs'
      preLoaderRoute: typeof DashboardSuperadminJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/index-analyzer': {
      id: '/_dashboard/superadmin/index-analyzer'
      path: '/superadmin/index-analyzer'
      fullPath: '/superadmin/index-analyzer'
      preLoaderRoute: typeof DashboardSuperadminIndexAnalyzerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/housekeeping': {
      id: '/_dashboard/superadmin/housekeeping'
      path: '/superadmin/housekeeping'
      fullPath: '/superadmin/housekeeping'
      preLoaderRoute: typeof DashboardSuperadminHousekeepingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/databases': {
      id: '/_dashboard/superadmin/databases'
      path: '/superadmin/databases'
      fullPath: '/superadmin/databases'
      preLoaderRoute: typeof DashboardSuperadminDatabasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/audit-logs': {
      id: '/_dashboard/superadmin/audit-logs'
      path: '/superadmin/audit-logs'
      fullPath: '/superadmin/audit-logs'
      preLoaderRoute: typeof DashboardSuperadminAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/application/$appId': {
      id: '/_dashboard/superadmin/application/$appId'
      path: '/superadmin/application/$appId'
      fullPath: '/superadmin/application/$appId'
      preLoaderRoute: typeof DashboardSuperadminApplicationAppIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardApplicationRoute: typeof DashboardApplicationRoute
  DashboardDictionaryRoute: typeof DashboardDictionaryRoute
  DashboardGeneratorRoute: typeof DashboardGeneratorRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardUnmappedRcRoute: typeof DashboardUnmappedRcRoute
  DashboardUploadsRoute: typeof DashboardUploadsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSuperadminAuditLogsRoute: typeof DashboardSuperadminAuditLogsRoute
  DashboardSuperadminDatabasesRoute: typeof DashboardSuperadminDatabasesRoute
  DashboardSuperadminHousekeepingRoute: typeof DashboardSuperadminHousekeepingRoute
  DashboardSuperadminIndexAnalyzerRoute: typeof DashboardSuperadminIndexAnalyzerRoute
  DashboardSuperadminJobsRoute: typeof DashboardSuperadminJobsRoute
  DashboardSuperadminUsersRoute: typeof DashboardSuperadminUsersRoute
  DashboardSuperadminIndexRoute: typeof DashboardSuperadminIndexRoute
  DashboardSuperadminApplicationAppIdRoute: typeof DashboardSuperadminApplicationAppIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApplicationRoute: DashboardApplicationRoute,
  DashboardDictionaryRoute: DashboardDictionaryRoute,
  DashboardGeneratorRoute: DashboardGeneratorRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardUnmappedRcRoute: DashboardUnmappedRcRoute,
  DashboardUploadsRoute: DashboardUploadsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSuperadminAuditLogsRoute: DashboardSuperadminAuditLogsRoute,
  DashboardSuperadminDatabasesRoute: DashboardSuperadminDatabasesRoute,
  DashboardSuperadminHousekeepingRoute: DashboardSuperadminHousekeepingRoute,
  DashboardSuperadminIndexAnalyzerRoute: DashboardSuperadminIndexAnalyzerRoute,
  DashboardSuperadminJobsRoute: DashboardSuperadminJobsRoute,
  DashboardSuperadminUsersRoute: DashboardSuperadminUsersRoute,
  DashboardSuperadminIndexRoute: DashboardSuperadminIndexRoute,
  DashboardSuperadminApplicationAppIdRoute:
    DashboardSuperadminApplicationAppIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
