{
 "title": "Dashboard Bale Korpora DGOD",
 "tags": [ "DGOD" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Bale Korpora", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jumlah Trx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT COUNT(*) AS jumlah FROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') "
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  },
  {
   "title": "Sukses : Error",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT\r\n  ROUND(COUNT(*) FILTER (WHERE \"IS_ERR\" = 'N')) as Sukses,\r\n  ROUND(COUNT(*) FILTER (WHERE \"IS_ERR\" = 'Y')) as Error\r\nFROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') "
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  },
  {
   "title": "Persentase Sukses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT\r\n  date_trunc('minute', \"ACTN_DT\" - interval '7 hour') as time,\r\n  ROUND(100.0 * COUNT(*) FILTER (WHERE \"IS_ERR\" = 'N')/ COUNT(*), 2) as persentase_sukses\r\nFROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') GROUP BY 1 "
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  },
  {
   "title": "Total Trx Sukses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT\r\n  date_trunc('minute', \"ACTN_DT\" - interval '7 hour') as time,\r\n  COUNT(*) FILTER (WHERE \"IS_ERR\" = 'N') as total_sukses\r\nFROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') GROUP BY 1 "
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  },
  {
   "title": "Persentase Error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT\r\n  date_trunc('minute', \"ACTN_DT\" - interval '7 hour') as time,\r\n  ROUND(100.0 * COUNT(*) FILTER (WHERE \"IS_ERR\" = 'Y')/ COUNT(*), 2) as persentase_sukses\r\nFROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') GROUP BY 1 "
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  },
  {
   "title": "Total Trx Error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT\r\n  date_trunc('minute', \"ACTN_DT\" - interval '7 hour') as time,\r\n  COUNT(*) FILTER (WHERE \"IS_ERR\" = 'Y') as total_sukses\r\nFROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') GROUP BY 1 "
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  },
  {
   "title": "Maximum Total Transaksi (Menit)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT   date_trunc('minute', \"ACTN_DT\" - interval '7 hour') as time, COUNT(*) AS jumlah FROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') GROUP BY time "
    }
   ]
  },
  {
   "title": "TPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT   date_trunc('minute', \"ACTN_DT\" - interval '7 hour') as time, COUNT(*) AS jumlah FROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') GROUP BY time "
    }
   ]
  },
  {
   "title": "Volume Trx Sukses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT\r\n  SUM(\"AMT\") AS volume\r\nFROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') AND \"IS_ERR\" = 'N' "
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  },
  {
   "title": "Volume Trx Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT\r\n  SUM(\"AMT\") AS volume\r\nFROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') AND \"IS_ERR\" = 'Y' "
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  },
  {
   "title": "TPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT\r\n  date_trunc('minute', \"ACTN_DT\" - interval '7 hour') as time,\r\n  COUNT(*) AS jumlah,\r\n  ROUND(100.0 * COUNT(*) FILTER (WHERE \"IS_ERR\" = 'N')/ COUNT(*), 2) as persentase_sukses\r\nFROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour') GROUP BY 1"
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  },
  {
   "title": "TOP 10 Error",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT \"ERR_MAP_CD\", COUNT(\"ERR_MAP_CD\") AS \"Error Map\"\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  AND \"IS_ERR\" = 'Y'\r\nGROUP BY \"ERR_MAP_CD\"\r\nORDER BY 2 DESC\r\nLIMIT 10"
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  },
  {
   "title": "TOP 10 Error",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT \"ERR_MAP_CD\", \"ERR_MAP_NM\", \"REF_NO\", \"ACTN_TYP_NM\",\r\n  split_part(\"TRX_STS_NM\", '.', array_length(string_to_array(\"TRX_STS_NM\", '.'), 1)) AS status\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  AND \"IS_ERR\" = 'Y'\r\nGROUP BY \"ERR_MAP_CD\", 2, 3, 4, 5\r\nORDER BY 2 DESC\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "TOP 10 Service Name",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "bale_korpora_db",
     "rawSql": "SELECT \"SRVC_NM\", COUNT(\"SRVC_NM\") AS \"Service Name\" FROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp + interval '7 hour') AND \"ACTN_DT\"  <= ($__timeTo()::timestamp + interval '7 hour')  GROUP BY \"SRVC_NM\" ORDER BY 2 DESC LIMIT 10"
    },
    {
     "dataset": "bale_korpora_db",
     "rawSql": "-- \"SRVC_NM\" = service name\r\n-- \"ACTN_DT\" = date -> format 2005-12-24 06:42:04\r\n-- \"ACCT_CCY_CD\" = currency\r\n-- \"AMT\" = amount\r\n-- \"IS_ERR\" = N (ga error)\r\n-- ERR_MAP_CD & ERR_MAP_NM \r\n-- \"ACTN_TYP_NM\" = action_type\r\n-- \"REF_NO\"\r\n\r\n-- \"TRX_STS_CD\" = CODE statusnya\r\n-- \"TRX_STS_NAME\" = transaksi status name\r\n-- 0001 = failoncreation\r\n-- 0002 = pendingapproval\r\n-- 0003 = approvalinprogress\r\n-- 0004 = rejected\r\n-- 0005 = pendingrelease\r\n-- 0006 = expired\r\n-- 0007 = pendingexecute\r\n-- 0008 = cancelled\r\n-- 0010 = inprogress\r\n-- 0011 = executedwithpartialsuccess\r\n-- 0011 = inprogressoffline\r\n-- 0012 = executedsuccessfully\r\n-- 0013 = executedsuccesfully\r\n-- 0013 = executewithfailure\r\n-- 0014 = executedwithpartialsuccess\r\n-- 0014 = executewithfailure\r\n-- 0015 = executionfail\r\n-- 0016 = notexecuted\r\n-- 0017 = failonrecurringcreation\r\n-- 0018 = pendingrepair\r\n-- 008 = cancelled\r\n-- 12 = executedsuccesfully\r\n-- 13 = executewithfailure\r\n\r\n-- CLASS = ActivityLog, FinancialActivityLog, NonFinancialActivityLog"
    }
   ]
  }
 ]
}