{
 "title": "Dashboard CMS - Development",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Jumlah Transaksi",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT \r\n  date_trunc('minute', \"ACTN_DT\") AS time,\r\n  count(\"ID\") AS \"Jumlah Trx\"\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE\r\n  \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- -- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 10\r\n\r\nSELECT\r\n    (SUM(CASE WHEN \"IS_ERR\" IN ('N') THEN 1 ELSE 0 END)::numeric / \r\n     NULLIF(COUNT(\"ID\"), 0)) * 100 AS \"Persentase\"\r\nFROM \"GCM_AGCM_LOG_ACTV\" \r\nWHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)\r\n\r\n\r\n-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" WHERE DATE(\"ACTN_DT\") = '2026-04-14' LIMIT 10"
    }
   ]
  },
  {
   "title": "Volume Trx Sukses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 10\r\n\r\nSELECT\r\n    SUM(\"AMT\") AS Volume\r\nFROM \"GCM_AGCM_LOG_ACTV\" \r\nWHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp) and (\"IS_ERR\" = 'N') AND \"AMT_CCY_CD\" = 'IDR'"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 10\r\n\r\nSELECT\r\n    SUM(CASE WHEN \"IS_ERR\" IN ('N') THEN 1 ELSE 0 END)::numeric AS \"Total N\",\r\n    SUM(CASE WHEN \"IS_ERR\" IN ('Y') THEN 1 ELSE 0 END)::numeric AS \"Total Y\"\r\nFROM \"GCM_AGCM_LOG_ACTV\" \r\nWHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT DISTINCT \"ACTN_TYP_NM\" FROM \"GCM_AGCM_LOG_ACTV\" \r\nSELECT \"ERR_MAP_CD\", COUNT(\"ERR_MAP_CD\") AS \"Error Map\" FROM \"GCM_AGCM_LOG_ACTV\" WHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)  GROUP BY \"ERR_MAP_CD\" ORDER BY 2 DESC LIMIT 10\r\n\r\n-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 10"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 10\r\n\r\nSELECT\r\n    (SUM(CASE WHEN \"IS_ERR\" IN ('Y') THEN 1 ELSE 0 END)::numeric / \r\n     NULLIF(COUNT(\"ID\"), 0)) * 100 AS \"Persentase\"\r\nFROM \"GCM_AGCM_LOG_ACTV\" \r\nWHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)"
    }
   ]
  },
  {
   "title": "Volume Trx Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 10\r\n\r\nSELECT\r\n    SUM(\"AMT\") AS Volume\r\nFROM \"GCM_AGCM_LOG_ACTV\" \r\nWHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp) and (\"IS_ERR\" = 'Y') AND \"AMT_CCY_CD\" = 'IDR'"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT \r\n  date_trunc('second', \"ACTN_DT\") AS time,\r\n  count(\"ID\") AS \"Jumlah Trx\"\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE\r\n  \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 10\r\n\r\nSELECT \r\n    date_trunc('minute',\"ACTN_DT\") AS time,\r\n    COUNT(\"ID\") AS total_transaksi,\r\n    (SUM(CASE WHEN \"IS_ERR\" IN ('N') THEN 1 ELSE 0 END)::numeric / \r\n     NULLIF(COUNT(\"ID\"), 0)) * 100 AS \"Persentase Sukses\"\r\nFROM \"GCM_AGCM_LOG_ACTV\" \r\nWHERE \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Single",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT\r\n    \"SRVC_NM\" AS \"Fitur\",\r\n    COUNT(*) AS \"Total\",\r\n    COUNT(*) FILTER (WHERE \"IS_ERR\" = 'N') AS \"Success\",\r\n    COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N') AS \"Failed\",\r\n    ROUND(\r\n        COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N')::numeric \r\n        / NULLIF(COUNT(*),0) * 100, 0\r\n    ) AS \"% Failed\"\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE \"SRVC_NM\" NOT ILIKE '%Payroll%' AND \"SRVC_NM\" NOT ILIKE '%BULK%'\r\nAND \"ACTN_TYP_NM\" ILIKE '%Execute%' AND \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)\r\nGROUP BY \"SRVC_NM\"\r\nORDER BY \"SRVC_NM\";"
    }
   ]
  },
  {
   "title": "Payroll",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT\r\n    \"SRVC_NM\" AS \"Fitur\",\r\n    COUNT(*) AS \"Total\",\r\n    COUNT(*) FILTER (WHERE \"IS_ERR\" = 'N') AS \"Success\",\r\n    COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N') AS \"Failed\",\r\n    ROUND(\r\n        COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N')::numeric \r\n        / NULLIF(COUNT(*),0) * 100, 0\r\n    ) AS \"% Failed\"\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE \"SRVC_NM\" ILIKE '%Payroll%' AND \"ACTN_TYP_NM\" ILIKE '%Execute%' AND \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)\r\nGROUP BY \"SRVC_NM\"\r\nORDER BY \"SRVC_NM\";"
    }
   ]
  },
  {
   "title": "Bulk",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT\r\n    \"SRVC_NM\" AS \"Fitur\",\r\n    COUNT(*) AS \"Total\",\r\n    COUNT(*) FILTER (WHERE \"IS_ERR\" = 'N') AS \"Success\",\r\n    COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N') AS \"Failed\",\r\nROUND(\r\n        COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N')::numeric \r\n        / NULLIF(COUNT(*),0) * 100, 0\r\n    ) AS \"% Failed\"\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE \"SRVC_NM\" ILIKE '%BULK%' AND \"ACTN_TYP_NM\" ILIKE '%Execute%' AND \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)\r\nGROUP BY \"SRVC_NM\"\r\nORDER BY \"SRVC_NM\";"
    }
   ]
  },
  {
   "title": "Payroll Detail",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT \r\n    \"ACTN_BY_CUST_ID\",\r\n    \"SRVC_NM\" AS \"Fitur\",\r\n    COUNT(*) AS \"Total\",\r\n    COUNT(*) FILTER (WHERE \"IS_ERR\" = 'N') AS \"Success\",\r\n    COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N') AS \"Failed\",\r\n    ROUND(\r\n        COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N')::numeric \r\n        / NULLIF(COUNT(*),0) * 100, 0\r\n    ) AS \"% Failed\",\r\n    STRING_AGG(DISTINCT \"TRX_STS_NM\", ', ') \r\n        FILTER (WHERE \"IS_ERR\" != 'N') AS \"Failed Type\"\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE \"SRVC_NM\" ILIKE '%Payroll%' \r\n  AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  AND \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)\r\nGROUP BY \r\n    \"ACTN_BY_CUST_ID\",\r\n    \"SRVC_NM\"\r\nORDER BY \"SRVC_NM\";"
    }
   ]
  },
  {
   "title": "Bulk Detail",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT \r\n    \"ACTN_BY_CUST_ID\",\r\n    \"SRVC_NM\" AS \"Fitur\",\r\n    COUNT(*) AS \"Total\",\r\n    COUNT(*) FILTER (WHERE \"IS_ERR\" = 'N') AS \"Success\",\r\n    COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N') AS \"Failed\",\r\n    ROUND(\r\n        COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N')::numeric \r\n        / NULLIF(COUNT(*),0) * 100, 0\r\n    ) AS \"% Failed\",\r\n    STRING_AGG(DISTINCT \"TRX_STS_NM\", ', ') \r\n        FILTER (WHERE \"IS_ERR\" != 'N') AS \"Failed Type\"\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE \"SRVC_NM\" ILIKE '%BULK%' \r\n  AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  AND \"ACTN_DT\"  >= ($__timeFrom()::timestamp) AND \"ACTN_DT\"  <= ($__timeTo()::timestamp)\r\nGROUP BY \r\n    \"ACTN_BY_CUST_ID\",\r\n    \"SRVC_NM\"\r\nORDER BY \"SRVC_NM\";"
    }
   ]
  },
  {
   "title": "Top 5 Type",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT \"ACTN_TYP_NM\",\r\n  COUNT(*) FILTER(WHERE \"IS_ERR\" = 'N') AS \"Success\",\r\n  COUNT(*) FILTER(WHERE \"IS_ERR\" = 'Y') AS \"Error\"\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_TYP_NM\" IS NOT NULL\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp)\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp)\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT \"ACTN_TYP_NM\",\r\n  COUNT(*) AS \"Total\",\r\n  COUNT(*) FILTER(WHERE \"IS_ERR\" = 'N') AS \"Success\",\r\n  COUNT(*) FILTER(WHERE \"IS_ERR\" = 'Y') AS \"Error\"\r\nFROM \"GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_TYP_NM\" IS NOT NULL\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp)\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp)\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 50"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT * FROM \"cms_db_GCM_AGCM_LOG_EXECUTION\"  LIMIT 10\r\n"
    }
   ]
  }
 ]
}