{
 "title": "Detail Watchlist Dashboard",
 "tags": [ "Watchlist" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "corp_name",
    "label": "Corporation",
    "query": "EDIK,\nFATMAWATI1,\nUSU123,\n176PTPJA,\nYAYASANUHN"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center; font-weight: 700; font-size: 3rem;\">\r\n  Dashboard Bale Korpora - ${corp_name:label}\r\n</h1>"
   }
  },
  {
   "title": "Total Transaction Execute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT \r\n  COUNT(\"ID\")\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE\r\n  \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n  AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n AND \"ACTN_DT\" >= ($__timeFrom() :: timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo() :: timestamp + interval '7 hour')\r\n\r\n-- SELECT * FROM \"bale_korpora_db_GCM_AGCM_LOG_ACTV\" LIMIT 1"
    }
   ]
  },
  {
   "title": "Transaction Success Execute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 50\r\n-- SELECT \"ID\", \"ACTN_DT\", \"ACTN_TYP_NM\", \"SRVC_NM\", \"AMT\", \"TRX_STS_CD\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\nSELECT\r\n  COUNT(*) AS jumlah_baris\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_BY_CUST_ID\" = '$corp_name'\r\nAND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  AND \"IS_ERR\" = 'N';"
    }
   ]
  },
  {
   "title": "Transaction Failed Execute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 50\r\n-- SELECT \"ID\", \"ACTN_DT\", \"ACTN_TYP_NM\", \"SRVC_NM\", \"AMT\", \"TRX_STS_CD\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\nSELECT\r\n  COUNT(*) AS jumlah_baris\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_BY_CUST_ID\" = '$corp_name'\r\nAND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  AND \"IS_ERR\" <> 'N';"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 50\r\n\r\n-- SELECT \"ID\", \"ACTN_DT\", \"ACTN_TYP_NM\", \"SRVC_NM\", \"AMT\", \"TRX_STS_CD\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\n\r\n\r\nSELECT\r\n    COUNT(CASE WHEN \"IS_ERR\" = 'N' THEN 1 END) AS \"Success\",\r\n    COUNT(CASE WHEN \"IS_ERR\" <> 'N' THEN 1 END) AS \"Failed\"\r\n\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n\r\n-- SELECT DISTINCT \"IS_ERR\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\";\r\n\r\n-- SELECT COUNT(*) AS jumlah_baris\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Top 5 ERR Name",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH err_counts AS (\r\n  SELECT\r\n    a.\"ERR_MAP_CD\",\r\n    COUNT(*) AS \"Count_ERR\"\r\n  FROM \"bale_korpora_db_GCM_AGCM_LOG_ACTV\" a\r\n  WHERE a.\"ACTN_BY_CUST_ID\" = '$corp_name'\r\n    AND a.\"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n    AND a.\"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n    AND a.\"IS_ERR\" = 'Y'\r\n  GROUP BY a.\"ERR_MAP_CD\"\r\n  ORDER BY 2 DESC\r\n  LIMIT 5\r\n)\r\nSELECT\r\n  e.\"ERR_MAP_CD\" || ' : ' || COALESCE(m.\"NM\", 'Anon') AS \"RC_ERR\",\r\n  e.\"Count_ERR\"\r\nFROM err_counts e\r\nLEFT JOIN \"bale_korpora_db_GCM_AGCM_HOST_ERROR_MAPPING\" m\r\n  ON e.\"ERR_MAP_CD\" = m.\"CD\"\r\nORDER BY e.\"Count_ERR\" DESC"
    }
   ]
  },
  {
   "title": "Volume Transaction (RP Juta)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT\r\n  SUM(\"AMT\") AS \"Volume\"\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'"
    }
   ]
  },
  {
   "title": "Volume TRX Success (RP Juta)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT\r\n--   SUM(\"AMT\") AS \"Volume\"\r\n-- FROM\r\n--   \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n--   AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n--   AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n--   AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n--   AND \"IS_ERR\" = 'N';\r\n\r\nSELECT\r\n  SUM(\"AMT\") AS \"Volume\"\r\nFROM \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  AND \"IS_ERR\" = 'N';"
    }
   ]
  },
  {
   "title": "Volume TRX Failed (RP Juta)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 50\r\n\r\n-- SELECT \"ID\", \"ACTN_DT\", \"ACTN_TYP_NM\", \"SRVC_NM\", \"AMT\", \"TRX_STS_CD\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\n\r\n\r\nSELECT COALESCE(SUM(\"AMT\"), 0) AS total_amt\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\nAND \"IS_ERR\" <> 'N';\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Total Transaction Inquiry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT \r\n  COUNT(\"ID\")\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE\r\n  \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n  AND \"ACTN_TYP_NM\" NOT ILIKE '%Execute%'\r\n AND \"ACTN_DT\" >= ($__timeFrom() :: timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo() :: timestamp + interval '7 hour')\r\n\r\n-- SELECT * FROM \"bale_korpora_db_GCM_AGCM_LOG_ACTV\" LIMIT 1"
    }
   ]
  },
  {
   "title": "Transaction Success Inquiry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 50\r\n-- SELECT \"ID\", \"ACTN_DT\", \"ACTN_TYP_NM\", \"SRVC_NM\", \"AMT\", \"TRX_STS_CD\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\nSELECT\r\n  COUNT(*) AS jumlah_baris\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_BY_CUST_ID\" = '$corp_name'\r\nAND \"ACTN_TYP_NM\" NOT ILIKE '%Execute%'\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  AND \"IS_ERR\" = 'N';"
    }
   ]
  },
  {
   "title": "Transaction Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 50\r\n-- SELECT \"ID\", \"ACTN_DT\", \"ACTN_TYP_NM\", \"SRVC_NM\", \"AMT\", \"TRX_STS_CD\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\nSELECT\r\n  COUNT(*) AS jumlah_baris\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_BY_CUST_ID\" = '$corp_name'\r\nAND \"ACTN_TYP_NM\" NOT ILIKE '%Execute%'\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  AND \"IS_ERR\" <> 'N';"
    }
   ]
  },
  {
   "title": "Single",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 50\r\n-- SELECT \"ID\", \"ACTN_DT\", \"ACTN_TYP_NM\", \"SRVC_NM\", \"AMT\", \"TRX_STS_CD\", \"IS_ERR\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\n-- SELECT\r\n--     COUNT(CASE WHEN \"IS_ERR\" = 'N' THEN 1 END) AS sukses,\r\n--     COUNT(CASE WHEN \"IS_ERR\" <> 'N' THEN 1 END) AS gagal\r\n-- FROM \"GCM_AGCM_LOG_ACTV\";\r\n-- SELECT DISTINCT \"SRVC_NM\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\";\r\n-- SELECT COUNT(*) AS jumlah_baris\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\nSELECT\r\n  \"SRVC_NM\" AS \"Fitur\",\r\n  COUNT(*) AS \"Total\",\r\n  COUNT(*) FILTER (\r\n    WHERE\r\n      \"IS_ERR\" = 'N'\r\n  ) AS \"Success\",\r\n  COUNT(*) FILTER (\r\n    WHERE\r\n      \"IS_ERR\" != 'N'\r\n  ) AS \"Reject\",\r\n  ROUND(\r\n    COUNT(*) FILTER (\r\n      WHERE\r\n        \"IS_ERR\" != 'N'\r\n    ) :: numeric / NULLIF(COUNT(*), 0) * 100,\r\n    0\r\n  ) AS \"% Failed\"\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE\r\n  \"SRVC_NM\" NOT ILIKE '%Payroll%'\r\n  AND \"SRVC_NM\" NOT ILIKE '%BULK%'\r\n  AND \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n  AND \"ACTN_DT\" >= ($__timeFrom() :: timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo() :: timestamp + interval '7 hour')\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\nGROUP BY\r\n  \"SRVC_NM\"\r\nORDER BY\r\n  \"SRVC_NM\";\r\n\r\n"
    }
   ]
  },
  {
   "title": "Bulk",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 50\r\n-- SELECT \"ID\", \"ACTN_DT\", \"ACTN_TYP_NM\", \"SRVC_NM\", \"AMT\", \"TRX_STS_CD\", \"IS_ERR\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\n-- SELECT\r\n--     COUNT(CASE WHEN \"IS_ERR\" = 'N' THEN 1 END) AS sukses,\r\n--     COUNT(CASE WHEN \"IS_ERR\" <> 'N' THEN 1 END) AS gagal\r\n-- FROM \"GCM_AGCM_LOG_ACTV\";\r\n-- SELECT DISTINCT \"SRVC_NM\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\";\r\n-- SELECT COUNT(*) AS jumlah_baris\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\nSELECT\r\n  \"SRVC_NM\" AS \"Fitur\",\r\n  COUNT(*) AS \"Total\",\r\n  COUNT(*) FILTER (\r\n    WHERE\r\n      \"IS_ERR\" = 'N'\r\n  ) AS \"Success\",\r\n  COUNT(*) FILTER (\r\n    WHERE\r\n      \"IS_ERR\" != 'N'\r\n  ) AS \"Reject\",\r\n  ROUND(\r\n    COUNT(*) FILTER (\r\n      WHERE\r\n        \"IS_ERR\" != 'N'\r\n    ) :: numeric / NULLIF(COUNT(*), 0) * 100,\r\n    0\r\n  ) AS \"% Failed\"\r\nFROM\r\n  \"GCM_AGCM_LOG_ACTV\"\r\nWHERE\r\n  \"SRVC_NM\" ILIKE '%BULK%'\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  AND \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY\r\n  \"SRVC_NM\"\r\nORDER BY\r\n  \"SRVC_NM\";\r\n"
    }
   ]
  },
  {
   "title": "Payroll",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "-- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 50\r\n-- SELECT \"ID\", \"ACTN_DT\", \"ACTN_TYP_NM\", \"SRVC_NM\", \"AMT\", \"TRX_STS_CD\", \"IS_ERR\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\n-- SELECT\r\n--     COUNT(CASE WHEN \"IS_ERR\" = 'N' THEN 1 END) AS sukses,\r\n--     COUNT(CASE WHEN \"IS_ERR\" <> 'N' THEN 1 END) AS gagal\r\n-- FROM \"GCM_AGCM_LOG_ACTV\";\r\n-- SELECT DISTINCT \"SRVC_NM\"\r\n-- FROM \"GCM_AGCM_LOG_ACTV\";\r\n-- SELECT COUNT(*) AS jumlah_baris\r\n-- FROM \"GCM_AGCM_LOG_ACTV\"\r\n-- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\nSELECT\r\n  \"SRVC_NM\" AS \"Fitur\",\r\n  COUNT(*) AS \"Total\",\r\n  COUNT(*) FILTER (\r\n    WHERE\r\n      \"IS_ERR\" = 'N'\r\n  ) AS \"Success\",\r\n  COUNT(*) FILTER (\r\n    WHERE\r\n      \"IS_ERR\" != 'N'\r\n  ) AS \"Reject\",\r\n  ROUND(\r\n    COUNT(*) FILTER (\r\n      WHERE\r\n        \"IS_ERR\" != 'N'\r\n    ) :: numeric / NULLIF(COUNT(*), 0) * 100,\r\n    0\r\n  ) AS \"% Failed\"\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE\r\n  \"SRVC_NM\" ILIKE '%Payroll%'\r\n  AND \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n  AND \"ACTN_DT\" >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo()::timestamp + interval '7 hour')\r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\nGROUP BY\r\n  \"SRVC_NM\"\r\nORDER BY\r\n  \"SRVC_NM\";"
    }
   ]
  },
  {
   "title": "Trend Total Transaction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT\r\n  \"ACTN_DT\" - INTERVAL '7 hour' AS \"Time\",\r\n  COUNT(*) AS \"Count_Record\"\r\nFROM\r\n  \"bale_korpora_db_GCM_AGCM_LOG_ACTV\"\r\nWHERE \"ACTN_BY_CUST_ID\" = '$corp_name'\r\n  AND \"ACTN_DT\" >= ($__timeFrom() :: timestamp + interval '7 hour')\r\n  AND \"ACTN_DT\" <= ($__timeTo() :: timestamp + interval '7 hour') \r\n  -- AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\nGROUP BY\r\n  \"ACTN_DT\"\r\nORDER BY\r\n  \"ACTN_DT\" DESC;\r\n  \r\n  -- SELECT * FROM \"GCM_AGCM_LOG_ACTV\" LIMIT 50\r\n  -- SELECT \"ID\", \"ACTN_DT\", \"ACTN_TYP_NM\", \"SRVC_NM\", \"AMT\", \"TRX_STS_CD\", \"IS_ERR\"\r\n  -- FROM \"GCM_AGCM_LOG_ACTV\"\r\n  -- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\n  -- SELECT\r\n  --     COUNT(CASE WHEN \"IS_ERR\" = 'N' THEN 1 END) AS sukses,\r\n  --     COUNT(CASE WHEN \"IS_ERR\" <> 'N' THEN 1 END) AS gagal\r\n  -- FROM \"GCM_AGCM_LOG_ACTV\";\r\n  -- SELECT DISTINCT \"SRVC_NM\"\r\n  -- FROM \"GCM_AGCM_LOG_ACTV\";\r\n  -- SELECT COUNT(*) AS jumlah_baris\r\n  -- FROM \"GCM_AGCM_LOG_ACTV\"\r\n  -- WHERE \"ACTN_TYP_NM\" ILIKE '%Execute'\r\n  -- SELECT \r\n  --     \"ACTN_BY_CUST_ID\",\r\n  --     \"SRVC_NM\" AS \"Fitur\",\r\n  --     COUNT(*) AS \"Total\",\r\n  --     COUNT(*) FILTER (WHERE \"IS_ERR\" = 'N') AS \"Success\",\r\n  --     COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N') AS \"Reject\",\r\n  --     ROUND(\r\n  --         COUNT(*) FILTER (WHERE \"IS_ERR\" != 'N')::numeric \r\n  --         / NULLIF(COUNT(*),0) * 100, 0\r\n  --     ) AS \"% Failed\"\r\n  -- FROM \"GCM_AGCM_LOG_ACTV\"\r\n  -- WHERE \"SRVC_NM\" NOT ILIKE '%Payroll%' \r\n  -- AND \"SRVC_NM\" NOT ILIKE '%BULK%' AND \"ACTN_TYP_NM\" ILIKE '%Execute%'\r\n  -- GROUP BY \r\n  --     \"ACTN_BY_CUST_ID\",\r\n  --     \"SRVC_NM\"\r\n  -- ORDER BY \"SRVC_NM\";"
    }
   ]
  },
  {
   "title": "Trend Failed Transaction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  }
 ]
}