-- DEPRECATED: MySQL not supported for new work. Use the .postgres.sql variant.

WITH categories AS (
    SELECT 'ACTIVATE_DORMANT' AS category UNION ALL
    SELECT 'BILLPAYMENT_BANK_LOAN' UNION ALL
    SELECT 'BILLPAYMENT_BPJS_KESEHATAN' UNION ALL
    SELECT 'BILLPAYMENT_BPJS_TENAGA_KERJA' UNION ALL
    SELECT 'BILLPAYMENT_CREDIT_CARD' UNION ALL
    SELECT 'BILLPAYMENT_CREDIT_CARD_OTHER' UNION ALL
    SELECT 'BILLPAYMENT_DONATION_ACT' UNION ALL
    SELECT 'BILLPAYMENT_DONATION_BAZNAS' UNION ALL
    SELECT 'BILLPAYMENT_DONATION_DOMPET' UNION ALL
    SELECT 'BILLPAYMENT_ECOM_BUKALAPAK' UNION ALL
    SELECT 'BILLPAYMENT_ECOM_TOKOPEDIA' UNION ALL
    SELECT 'BILLPAYMENT_EDUCATION' UNION ALL
    SELECT 'BILLPAYMENT_INSURANCE' UNION ALL
    SELECT 'BILLPAYMENT_INTERNET_TV' UNION ALL
    SELECT 'BILLPAYMENT_MPN' UNION ALL
    SELECT 'BILLPAYMENT_MULTIBILLER' UNION ALL
    SELECT 'BILLPAYMENT_MULTIBILLER_LEGAL' UNION ALL
    SELECT 'BILLPAYMENT_NON_PBB' UNION ALL
    SELECT 'BILLPAYMENT_OTHER_LOAN' UNION ALL
    SELECT 'BILLPAYMENT_PBB' UNION ALL
    SELECT 'BILLPAYMENT_PDAM' UNION ALL
    SELECT 'BILLPAYMENT_PEGADAIAN' UNION ALL
    SELECT 'BILLPAYMENT_PGN' UNION ALL
    SELECT 'BILLPAYMENT_PHONE' UNION ALL
    SELECT 'BILLPAYMENT_PLN' UNION ALL
    SELECT 'BILLPAYMENT_TICKET_TRAIN' UNION ALL
    SELECT 'BILLPAYMENT_TRANSPORTATION' UNION ALL
    SELECT 'BILLPAYMENT_VA' UNION ALL
    SELECT 'BILLPAYMENT_VA_MORTGAGE' UNION ALL
    SELECT 'BILLPAYMENT_VEHICLE_TAX' UNION ALL
    SELECT 'BUY_MUTUAL_FUND' UNION ALL
    SELECT 'BUY_SBN' UNION ALL
    SELECT 'CARDLESS_DEPOSIT' UNION ALL
    SELECT 'CARDLESS_WITHDRAWAL' UNION ALL
    SELECT 'EDEPOSITO_PLACEMENT' UNION ALL
    SELECT 'EDEPOSITO_WITHDRAWAL' UNION ALL
    SELECT 'FREEZE_PROXY_BIFAST' UNION ALL
    SELECT 'MONEY_CHANGER' UNION ALL
    SELECT 'PORTING_PROXY_BIFAST' UNION ALL
    SELECT 'PURCHASE_EVOUCHER_MTIX' UNION ALL
    SELECT 'PURCHASE_EVOUCHER_STREAMING' UNION ALL
    SELECT 'PURCHASE_NFC_EMONEY' UNION ALL
    SELECT 'PURCHASE_NFC_FLAZZ' UNION ALL
    SELECT 'PURCHASE_NFC_TAPCASH' UNION ALL
    SELECT 'PURCHASE_PHONE' UNION ALL
    SELECT 'PURCHASE_PLN_PREPAID' UNION ALL
    SELECT 'PURCHASE_TOPUP_DANA' UNION ALL
    SELECT 'PURCHASE_TOPUP_GOPAY' UNION ALL
    SELECT 'PURCHASE_TOPUP_ISAKU' UNION ALL
    SELECT 'PURCHASE_TOPUP_LINKAJA' UNION ALL
    SELECT 'PURCHASE_TOPUP_OVO' UNION ALL
    SELECT 'PURCHASE_TOPUP_POSPAY' UNION ALL
    SELECT 'PURCHASE_TOPUP_SHOPEEPAY' UNION ALL
    SELECT 'QR_CROSS_BORDER' UNION ALL
    SELECT 'QR_MPM' UNION ALL
    SELECT 'REGISTRATION_PROXY_BIFAST' UNION ALL
    SELECT 'SELL_MUTUAL_FUND' UNION ALL
    SELECT 'SWITCH_FROM_MUTUAL_FUND' UNION ALL
    SELECT 'SWITCH_TO_MUTUAL_FUND' UNION ALL
    SELECT 'TRANSFER_ALL' UNION ALL
    SELECT 'TRANSFER_BIFAST' UNION ALL
    SELECT 'TRANSFER_FOREX_OA' UNION ALL
    SELECT 'TRANSFER_FOREX_ON_US' UNION ALL
    SELECT 'TRANSFER_OA' UNION ALL
    SELECT 'TRANSFER_OFF_US' UNION ALL
    SELECT 'TRANSFER_ON_US' UNION ALL
    SELECT 'TRANSFER_RTGS' UNION ALL
    SELECT 'TRANSFER_SKN' UNION ALL
    SELECT 'TRANSFER_SPLIT_BILL' UNION ALL
    SELECT 'TRANSFER_SWIFT' UNION ALL
    SELECT 'UNFREEZE_PROXY_BIFAST' UNION ALL
    SELECT 'UNREGISTRATION_PROXY_BIFAST' UNION ALL
    SELECT 'UPDATE_PROXY_BIFAST'
)

SELECT 
    DATE_FORMAT(rb.transaction_date, '%Y-%m-%d') AS `Tanggal Transaksi`,
    rb.transaction_category AS `Jenis Transaksi`,
    rb.result_code AS `RC`,
    rb.result_code_desc AS `RC Description`,
    COUNT(DISTINCT rb.id) AS `total transaksi`,
    SUM(rb.transaction_amount) AS `Total Nominal`,
    SUM(rb.transaction_fee) AS `Total Biaya Admin`,
    CASE  
        WHEN rb.transaction_status = 0 THEN 'Success' 
        WHEN rb.transaction_status = 1 THEN 'Failed' 
        WHEN rb.transaction_status = 2 THEN 'Pending' 
        WHEN rb.transaction_status = 9 THEN 'ACK' 
        WHEN rb.transaction_status = 8 THEN 'REVERSAL' 
        ELSE 'Status Tidak Dikenal' 
    END AS `Status Transaksi`
FROM bale_db.raw_bale rb
JOIN categories c 
    ON rb.transaction_category = c.category
WHERE 
    rb.transaction_state IN ('1','9','8')
    AND rb.transaction_date BETWEEN ? AND ?
GROUP BY 
    `Tanggal Transaksi`,
    rb.transaction_category,
    rb.result_code,
    rb.result_code_desc,
    rb.transaction_status
ORDER BY 
    `Tanggal Transaksi` DESC;

