// Auto-generated by PolyRPC - DO NOT EDIT
// Type-safe Python API client
// https://polyrpc.vercel.app

// ============ Models ============

export interface DbApp {
  app_id: string;
  app_name: string;
}

export interface GenerateDbRequest {
  app_name: string;
  app_id: string;
  master_date_from: string;
  master_date_to: string;
}

export interface GenerateResponse {
  app_name: string;
  output_path?: string | null;
  success: boolean;
  message: string;
}

export interface HealthResponse {
  status: string;
  db_configured: boolean;
  db_connected: boolean;
}

export interface MappingInfo {
  name: string;
  app_id: string;
  generate_from?: string;
}

export interface ReportInfo {
  filename: string;
  path: string;
  size_bytes: number;
  created_at: string;
}

export type FileResponse = Blob;

// ============ PolyRPC Client ============

const BASE_URL = 'http://localhost:8321';

export class PolyRPCError extends Error {
  constructor(
    message: string,
    public status: number,
    public data?: unknown
  ) {
    super(message);
    this.name = 'PolyRPCError';
  }
}

async function request<TOutput>(
  method: string,
  path: string,
  body?: unknown,
  query?: Record<string, unknown>
): Promise<TOutput> {
  let url = `${BASE_URL}${path}`;
  
  // Add query parameters
  if (query) {
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(query)) {
      if (value !== undefined && value !== null) {
        params.append(key, String(value));
      }
    }
    const queryString = params.toString();
    if (queryString) {
      url += `?${queryString}`;
    }
  }
  
  const response = await fetch(url, {
    method,
    headers: {
      'Content-Type': 'application/json',
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!response.ok) {
    let errorData: unknown;
    try {
      errorData = await response.json();
    } catch {
      errorData = await response.text();
    }
    throw new PolyRPCError(
      `Request failed: ${response.status} ${response.statusText}`,
      response.status,
      errorData
    );
  }

  return response.json();
}

export interface SubscribeOptions<T> {
  onData: (data: T) => void;
  onError?: (error: Error) => void;
  onComplete?: () => void;
}

function subscribe<T>(
  path: string,
  query?: Record<string, unknown>,
  options?: SubscribeOptions<T>
): { unsubscribe: () => void } {
  let url = `${BASE_URL}${path}`;
  
  // Add query parameters
  if (query) {
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(query)) {
      if (value !== undefined && value !== null) {
        params.append(key, String(value));
      }
    }
    const queryString = params.toString();
    if (queryString) {
      url += `?${queryString}`;
    }
  }
  
  const controller = new AbortController();
  
  (async () => {
    try {
      const response = await fetch(url, {
        method: 'GET',
        headers: {
          'Accept': 'text/event-stream',
        },
        signal: controller.signal,
      });
      
      if (!response.ok) {
        throw new PolyRPCError(
          `Stream failed: ${response.status} ${response.statusText}`,
          response.status
        );
      }
      
      const reader = response.body?.getReader();
      if (!reader) {
        throw new Error('No response body');
      }
      
      const decoder = new TextDecoder();
      let buffer = '';
      
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';
        
        for (const line of lines) {
          if (line.startsWith('data: ')) {
            const data = line.slice(6);
            if (data === '[DONE]') {
              options?.onComplete?.();
              return;
            }
            try {
              const parsed = JSON.parse(data) as T;
              options?.onData(parsed);
            } catch {
              // If not JSON, pass as string
              options?.onData(data as T);
            }
          }
        }
      }
      
      options?.onComplete?.();
    } catch (error) {
      if ((error as Error).name !== 'AbortError') {
        options?.onError?.(error as Error);
      }
    }
  })();
  
  return {
    unsubscribe: () => controller.abort(),
  };
}

// ============ Type-Safe Client ============

export const py = {
  apps: {
    list_db_apps_endpoint: {
      query: () => request<DbApp[]>('GET', '/apps/db'),
    },
    list_mappings: {
      query: () => request<MappingInfo[]>('GET', '/apps/mappings'),
    },
  },
  generate: {
    generate_db: {
      mutate: (input: GenerateDbRequest) => request<GenerateResponse>('POST', '/generate/db', input),
    },
    generate_excel: {
      mutate: () => request<GenerateResponse>('POST', '/generate/excel'),
    },
    generate_synthetic: {
      mutate: () => request<GenerateResponse>('POST', '/generate/synthetic'),
    },
  },
  health: {
    health: {
      query: () => request<HealthResponse>('GET', '/health'),
    },
  },
  reports: {
    list_reports: {
      query: () => request<ReportInfo[]>('GET', '/reports'),
    },
    download_report: {
      query: (input: { filename: string | number }) => request<FileResponse>('GET', `/reports/${input.filename}`),
    },
    delete_report: {
      mutate: (input: { filename: string | number }) => request<Record<string, string>>('DELETE', `/reports/${input.filename}`),
    },
  },
} as const;

export type PolyRPCClient = typeof py;
