{
 "title": "Daily Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Recap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<h1>\n  <p style=\"font-size: 35px;\">\n    <b>Bale by BTN</b>\n  </p>\n    </h1>\n</div>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "bale_db",
     "rawSql": "WITH base AS (\r\n    SELECT\r\n        th.transaction_id,\r\n        th.transaction_date,\r\n        th.result_code::text AS result_code,\r\n        th.transaction_category\r\n    FROM raw_bale th\r\n    WHERE\r\n        th.transaction_state IN ('1','9','8')\r\n        AND th.transaction_date BETWEEN ($__timeFrom()::timestamp + INTERVAL '7 hour')\r\n                                    AND ($__timeTo()::timestamp + INTERVAL '7 hour')\r\n        AND th.transaction_category = ANY(ARRAY[\r\n            'ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN',\r\n            'BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD',\r\n            'BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT',\r\n            'BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET',\r\n            'BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA',\r\n            'BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE',\r\n            'BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER',\r\n            'BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB',\r\n            'BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM',\r\n            'BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE',\r\n            'BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN',\r\n            'BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA',\r\n            'BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX',\r\n            'BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT',\r\n            'CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST',\r\n            'MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX',\r\n            'PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY',\r\n            'PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE',\r\n            'PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY',\r\n            'PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA',\r\n            'PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY',\r\n            'PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM',\r\n            'REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND',\r\n            'SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL',\r\n            'TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US',\r\n            'TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS',\r\n            'TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT',\r\n            'UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST',\r\n            'UPDATE_PROXY_BIFAST'\r\n        ])\r\n),\r\nbase_enriched AS (\r\n    SELECT\r\n        b.transaction_id,\r\n        b.transaction_date,\r\n        dc.error_type,\r\n        b.result_code\r\n    FROM base b\r\n    LEFT JOIN response_code_dictionary dc\r\n        ON b.result_code = dc.rc       \r\n        AND b.transaction_category = dc.jenis_transaksi\r\n        AND dc.id_app_identifier = 1\r\n),\r\nJumlah AS (\r\n    SELECT COUNT(DISTINCT transaction_id) AS total_transaksi\r\n    FROM base_enriched\r\n),\r\nPersentase AS (\r\n    SELECT\r\n        SUM(\r\n      CASE \r\n        WHEN b.error_type = 'Sukses'\r\n          OR b.result_code IS NULL\r\n          OR b.result_code = ''\r\n          OR b.error_type = 'N'\r\n        THEN 1 ELSE 0 \r\n      END\r\n    )::numeric / NULLIF(COUNT(DISTINCT b.transaction_id), 0) * 100 AS success_rate\r\n    FROM base_enriched b\r\n),\r\nRata AS (\r\n    SELECT AVG(per_second) AS \"TPS\"\r\n    FROM (\r\n        SELECT\r\n            date_trunc('second', transaction_date - INTERVAL '7 hour') AS time,\r\n            COUNT(*) AS per_second\r\n        FROM base_enriched\r\n        WHERE transaction_date >= ($__timeTo()::timestamp)   \r\n        GROUP BY 1\r\n    ) tps_sub\r\n)\r\nSELECT\r\n    j.total_transaksi,\r\n    r.\"TPS\",\r\n    p.success_rate\r\nFROM Jumlah j\r\nCROSS JOIN Rata r\r\nCROSS JOIN Persentase p;"
    }
   ]
  },
  {
   "title": "Jumlah Transaksi dan Persentase Sukses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "SELECT date_trunc('minute', th.transaction_date  - interval '7 hour') AS time,\r\nCOUNT(th.transaction_id) AS total_transaksi,\r\n  SUM(CASE\r\n    WHEN dc.error_type = 'Sukses' OR th.result_code IS NULL OR th.result_code = '' OR dc.error_type = 'N'\r\n    THEN 1 ELSE 0\r\n  END)::numeric / NULLIF(COUNT(DISTINCT th.transaction_id), 0) * 100 AS success_rate\r\nFROM raw_bale th\r\nLEFT JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc\r\n  AND th.transaction_category = dc.jenis_transaksi\r\n  AND dc.id_app_identifier = 1\r\nWHERE th.transaction_state IN ('1','9','8')\r\n  AND th.transaction_category = ANY(ARRAY['ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN','BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD','BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT','BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET','BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA','BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE','BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER','BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB','BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM','BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE','BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN','BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA','BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX','BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT','CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST','MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX','PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY','PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE','PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY','PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA','PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY','PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM','REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND','SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL','TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US','TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS','TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT','UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST','UPDATE_PROXY_BIFAST'])\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<h1>\n  <p style=\"font-size: 35px;\">\n    <b>Bale Bisnis</b>\n  </p>\n    </h1>\n</div>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH base AS (\r\n  SELECT\r\n    th.transaction_id,\r\n    th.transaction_date,\r\n    th.result_code,\r\n    th.transaction_category\r\n  FROM raw_bale_bisnis th\r\n  WHERE th.transaction_state IN ('0','1','2','3','4')\r\n        AND th.transaction_status IN ('0','1','2','3','4')\r\n        AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') \r\n        AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\n),\r\n\r\nPersentase AS (\r\n  SELECT\r\n    date_trunc('minute', b.transaction_date - interval '7 hour') AS time,\r\n    SUM(\r\n      CASE \r\n        WHEN dc.error_type = 'Sukses' OR b.result_code IS NULL OR b.result_code = ''\r\n          OR dc.error_type = 'N'\r\n        THEN 1 ELSE 0 \r\n      END\r\n    )::numeric / NULLIF(COUNT(DISTINCT b.transaction_id), 0) * 100 AS success_rate\r\n  FROM base b\r\n  LEFT JOIN response_code_dictionary dc \r\n    ON b.result_code = dc.rc AND b.transaction_category = dc.jenis_transaksi AND dc.id_app_identifier = 2\r\n  GROUP BY 1\r\n),\r\n\r\nJumlah AS (\r\n  SELECT COUNT(DISTINCT transaction_id) AS total_transaksi\r\n  FROM base\r\n),\r\n\r\nRata AS (\r\n  SELECT date_trunc('second', th.transaction_date - interval '7 hour') as time,\r\n  count(*) AS ratarata\r\nFROM base th\r\nWHERE\r\n  th.transaction_date >= $__timeTo() :: date - interval '7 hour'\r\nGROUP BY 1\r\nORDER BY 1 DESC\r\n)\r\n\r\nSELECT \r\n  j.total_transaksi,\r\n  AVG(r.ratarata) AS \"TPS\",\r\n  AVG(p.success_rate) AS \"Success Rate\"\r\nFROM Rata r\r\nCROSS JOIN Jumlah j\r\nCROSS JOIN Persentase p\r\nGROUP BY j.total_transaksi\r\n\r\n"
    }
   ]
  },
  {
   "title": "Jumlah Transaksi dan Persentase Sukses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.transaction_category,\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.transaction_id) AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            th.transaction_date,\r\n            th.transaction_id,\r\n            th.transaction_category,\r\n            th.result_code,\r\n            dc.error_type AS status_transaksi\r\n        FROM raw_bale_bisnis th\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON th.result_code = dc.rc\r\n            AND th.transaction_category = dc.jenis_transaksi\r\n            AND dc.id_app_identifier = 2\r\n        WHERE th.transaction_state IN ('0','1','2','3','4')\r\n          AND th.transaction_status IN ('0','1','2','3','4')\r\n          AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour')\r\n          AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.transaction_category,\r\n        t.status_transaksi,\r\n        t.result_code\r\n)\r\n\r\nSELECT\r\n    date_trunc('minute', sr.transaction_date - interval '7 hour')\r\n      - (extract(minute from sr.transaction_date - interval '7 hour')::int % 60) * interval '1 minute' AS time,\r\n    SUM(sr.total_transaksi) AS total_transaksi,\r\n    (\r\n        SUM(CASE\r\n            WHEN sr.status_transaksi IN ('Sukses', 'N')\r\n            THEN sr.total_transaksi\r\n            ELSE 0\r\n        END)::numeric\r\n        /\r\n        NULLIF(SUM(sr.total_transaksi), 0)\r\n    ) * 100 AS \"Persentase Sukses\"\r\nFROM data2 sr\r\nWHERE sr.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour')\r\n  AND sr.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<h1>\n  <p style=\"font-size: 35px;\">\n    <b>EDC Agent</b>\n  </p>\n    </h1>\n</div>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "bale_db",
     "rawSql": "WITH edc AS (\r\n    SELECT\r\n        TO_TIMESTAMP(\r\n            SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n            LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1), 6, '0'),\r\n            'YYMMDDHH24MISS'\r\n        ) AS transaction_date,\r\n        tr.\"TRRSPC\" AS result_code,\r\n        tr.\"TRSTAN\",\r\n        dc.error_type AS status_transaksi\r\n    FROM \"ASID160448_ZTRANS0P\" tr\r\n    LEFT JOIN response_code_dictionary dc\r\n        ON tr.\"TRRSPC\"::text = dc.rc\r\n        AND dc.id_app_identifier = 7\r\n    WHERE\r\n        tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n        AND tr.\"TRPROD\" = 'POS'\r\n),\r\nJumlah AS (\r\n    SELECT COUNT(\"TRSTAN\") AS total_transaksi\r\n    FROM edc\r\n    WHERE transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n),\r\nRata AS (\r\n    SELECT AVG(daily_count) AS \"TPS\"\r\n    FROM (\r\n        SELECT\r\n            date_trunc('second', transaction_date - INTERVAL '7 hour') AS time,\r\n            COUNT(\"TRSTAN\") AS daily_count\r\n        FROM edc\r\n        WHERE transaction_date >= $__timeTo()::date - INTERVAL '7 hour'\r\n        GROUP BY 1\r\n    ) sub\r\n),\r\nPersentase AS (\r\n    SELECT\r\n        AVG(\r\n            SUM(CASE \r\n                WHEN status_transaksi IN ('Sukses', 'N') \r\n                  OR result_code IS NULL \r\n                  OR result_code = '' \r\n                THEN 1 ELSE 0 \r\n            END)::numeric / NULLIF(COUNT(\"TRSTAN\"), 0) * 100\r\n        ) OVER () AS \"Success Rate\"\r\n    FROM edc\r\n    WHERE transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n    GROUP BY date_trunc('minute', transaction_date - INTERVAL '7 hour')\r\n    LIMIT 1\r\n)\r\nSELECT\r\n    j.total_transaksi,\r\n    r.\"TPS\",\r\n    p.\"Success Rate\"\r\nFROM Jumlah j\r\nCROSS JOIN Rata r\r\nCROSS JOIN Persentase p;"
    }
   ]
  },
  {
   "title": "Jumlah Transaksi dan Persentase Sukses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT \r\n    date_trunc('minute', sr.transaction_date ) \r\n  - (extract(minute from sr.transaction_date)::int % 3) * interval '1 minute' AS time,\r\n    SUM(sr.total_transaksi) AS total_transaksi,\r\n    (\r\n        SUM(CASE \r\n            WHEN sr.status_transaksi IN ('Sukses', 'N')\r\n            THEN sr.total_transaksi \r\n            ELSE 0 \r\n        END)::numeric\r\n        /\r\n        NULLIF(SUM(sr.total_transaksi), 0)\r\n    ) * 100 AS \"Persentase Sukses\"\r\nFROM data2 sr\r\nWHERE sr.transaction_date >= $__timeFrom()::timestamp\r\n  AND sr.transaction_date <= $__timeTo()::timestamp\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<h1>\n  <p style=\"font-size: 35px;\">\n    <b>EDC Merchant</b>\n  </p>\n    </h1>\n</div>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "bale_db",
     "rawSql": "WITH edc AS (\r\n    SELECT\r\n        TO_TIMESTAMP(\r\n            SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n            LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1), 6, '0'),\r\n            'YYMMDDHH24MISS'\r\n        ) AS transaction_date,\r\n        tr.\"TRRSPC\" AS result_code,\r\n        tr.\"TRSTAN\",\r\n        dc.error_type AS status_transaksi\r\n    FROM \"ASID160448_ZTRANS0P\" tr\r\n    LEFT JOIN response_code_dictionary dc\r\n        ON tr.\"TRRSPC\"::text = dc.rc\r\n        AND dc.id_app_identifier = 6\r\n    WHERE\r\n        tr.\"TRTRTY\" = '21'\r\n        AND tr.\"TRPROD\" = 'POS'\r\n),\r\nJumlah AS (\r\n    SELECT COUNT(\"TRSTAN\") AS total_transaksi\r\n    FROM edc\r\n    WHERE transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n),\r\nRata AS (\r\n    SELECT AVG(daily_count) AS \"TPS\"\r\n    FROM (\r\n        SELECT\r\n            date_trunc('second', transaction_date - INTERVAL '7 hour') AS time,\r\n            COUNT(\"TRSTAN\") AS daily_count\r\n        FROM edc\r\n        WHERE transaction_date >= $__timeTo()::date - INTERVAL '7 hour'\r\n        GROUP BY 1\r\n    ) sub\r\n),\r\nPersentase AS (\r\n    SELECT\r\n        AVG(\r\n            SUM(CASE \r\n                WHEN status_transaksi IN ('Sukses', 'N') \r\n                  OR result_code IS NULL \r\n                  OR result_code = '' \r\n                THEN 1 ELSE 0 \r\n            END)::numeric / NULLIF(COUNT(\"TRSTAN\"), 0) * 100\r\n        ) OVER () AS \"Success Rate\"\r\n    FROM edc\r\n    WHERE transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n    GROUP BY date_trunc('minute', transaction_date - INTERVAL '7 hour')\r\n    LIMIT 1\r\n)\r\nSELECT\r\n    j.total_transaksi,\r\n    r.\"TPS\",\r\n    p.\"Success Rate\"\r\nFROM Jumlah j\r\nCROSS JOIN Rata r\r\nCROSS JOIN Persentase p;"
    }
   ]
  },
  {
   "title": "Jumlah Transaksi dan Persentase Sukses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND dc.id_app_identifier = 6\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT \r\n    date_trunc('minute', sr.transaction_date) \r\n  - (extract(minute from sr.transaction_date)::int % 3) * interval '1 minute' AS time,\r\n    SUM(sr.total_transaksi) AS total_transaksi,\r\n    (\r\n        SUM(CASE \r\n            WHEN sr.status_transaksi IN ('Sukses', 'N')\r\n            THEN sr.total_transaksi \r\n            ELSE 0 \r\n        END)::numeric\r\n        /\r\n        NULLIF(SUM(sr.total_transaksi), 0)\r\n    ) * 100 AS \"Persentase Sukses\"\r\nFROM data2 sr\r\n-- JOIN app_identifier ai\r\n--   ON bl.id_app_identifier = ai.id\r\nWHERE $__timeFilter(sr.transaction_date)\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<h1>\n  <p style=\"font-size: 35px;\">\n    <b>EDC Merchant Ancol\n    </b>\n  </p>\n    </h1>\n</div>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "bale_db",
     "rawSql": "WITH edc AS (\n    SELECT\n        TO_TIMESTAMP(\n            SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\n            LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1), 6, '0'),\n            'YYMMDDHH24MISS'\n        ) AS transaction_date,\n        tr.\"TRRSPC\" AS result_code,\n        tr.\"TRSTAN\",\n        dc.error_type AS status_transaksi\n    FROM \"ASID160448_ZTRANS0P\" tr\n    LEFT JOIN response_code_dictionary dc\n        ON tr.\"TRRSPC\"::text = dc.rc\n        AND dc.id_app_identifier = 61\n    WHERE\n        tr.\"TRTRTY\" = '21'\n        AND tr.\"TRPROD\" = 'POS'\n            AND \"TRCAID\" IN (\n            '200719398140682',\n            '200719389813135',\n            '200719389808836',\n            '200719389810345',\n            '200719389819715',\n            '200719389812202',\n            '200719389815991',\n            '200719389809769',\n            '200719389811278',\n            '200719392283028',\n            '200719392284951',\n            '200719392281161',\n            '200719392293973',\n            '200719392300602',\n            '200719392299553',\n            '200719389824014',\n            '200719389830246',\n            '200719389828737',\n            '200719392280238',\n            '200719392277795',\n            '200719389823080',\n            '200719389827804',\n            '200719392276862',\n            '200719389829660',\n            '200719392297696',\n            '200719392298620',\n            '200719389825947',\n            '200719389826870',\n            '200719392286818',\n            '200719392279652',\n            '200719392295830',\n            '200719392294907',\n            '200719392296763',\n            '200719392285884',\n            '200719389831179',\n            '200719392278729',\n            '200719392301535',\n            '200719389801323',\n            '200719389800399',\n            '200719389822157',\n            '200719392271216',\n            '200719392273072',\n            '200719392274006',\n            '200719389821224',\n            '200719392272149',\n            '200719389820290',\n            '200719392275939',\n            '160016154115765',\n            '160016154115772',\n            '160016154115777',\n            '160016154115778',\n            '160016154115780',\n            '160016154115781',\n            '160016154115783',\n            '160016154115785',\n            '160016154115773',\n            '160016154115775',\n            '160016154115774',\n            '160016154115776',\n            '160016154115771',\n            '160016154115779',\n            '160016154115770',\n            '160016154115782',\n            '160016154115769',\n            '160016154115766',\n            '160016154115767',\n            '160016154115768',\n            '160016154115784',\n            '160016154115786',\n            '160016154115787',\n            '160016154115788',\n            '160016154115789',\n            '160016154115790',\n            '160016154115791',\n            '160016154115792',\n            '160016158125758',\n            '160016158125731',\n            '160016158125759',\n            '160016154115764',\n            '160016158125760',\n            '160016158125761',\n            '160016158125762',\n            '160016158125763'\n            )\n),\nJumlah AS (\n    SELECT COUNT(\"TRSTAN\") AS total_transaksi\n    FROM edc\n    WHERE transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\n),\nRata AS (\n    SELECT AVG(daily_count) AS \"TPS\"\n    FROM (\n        SELECT\n            date_trunc('second', transaction_date - INTERVAL '7 hour') AS time,\n            COUNT(\"TRSTAN\") AS daily_count\n        FROM edc\n        WHERE transaction_date >= $__timeTo()::date - INTERVAL '7 hour'\n        GROUP BY 1\n    ) sub\n),\nPersentase AS (\n    SELECT\n        AVG(\n            SUM(CASE \n                WHEN status_transaksi IN ('Sukses', 'N') \n                  OR result_code IS NULL \n                  OR result_code = '' \n                THEN 1 ELSE 0 \n            END)::numeric / NULLIF(COUNT(\"TRSTAN\"), 0) * 100\n        ) OVER () AS \"Success Rate\"\n    FROM edc\n    WHERE transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\n    GROUP BY date_trunc('minute', transaction_date - INTERVAL '7 hour')\n    LIMIT 1\n)\nSELECT\n    j.total_transaksi,\n    r.\"TPS\",\n    p.\"Success Rate\"\nFROM Jumlah j\nCROSS JOIN Rata r\nCROSS JOIN Persentase p;"
    }
   ]
  },
  {
   "title": "Jumlah Transaksi dan Persentase Sukses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\n\r\nSELECT \r\n    date_trunc('minute', sr.transaction_date) \r\n  - (extract(minute from sr.transaction_date)::int % 3) * interval '1 minute' AS time,\r\n    SUM(sr.total_transaksi) AS total_transaksi,\r\n    (\r\n        SUM(CASE \r\n            WHEN sr.status_transaksi IN ('Sukses', 'N')\r\n            THEN sr.total_transaksi \r\n            ELSE 0 \r\n        END)::numeric\r\n        /\r\n        NULLIF(SUM(sr.total_transaksi), 0)\r\n    ) * 100 AS \"Persentase Sukses\"\r\nFROM data2 sr\r\nWHERE $__timeFilter(sr.transaction_date)\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<h1>\n  <p style=\"font-size: 35px;\">\n    <b>Debit Online</b>\n  </p>\n    </h1>\n</div>"
   }
  },
  {
   "title": "Jumlah Trx",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "bale_db",
     "rawSql": "WITH data AS (\r\nSELECT (TO_TIMESTAMP(SUBSTRING(\"TRTDAT\"::text, 2) || \r\n    LPAD(SUBSTRING(\"TRTTIM\"::text FROM 1),6,'0'),\r\n      'YYMMDDHH24MISS') - interval '7 hour')::timestamp AS time,\r\n      COUNT(*) AS jumlah\r\n      FROM \"itm_db_ASID160448_ZTRANS0P\" \r\n      WHERE \r\n        \"TRTRTY\" = '21' AND \"TRPCCD\" = 59\r\n      GROUP BY 1\r\n)     \r\n\r\nSELECT * FROM data \r\nWHERE $__timeFilter(time) \r\n"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "bale_db",
     "rawSql": "WITH data AS (\r\nSELECT (TO_TIMESTAMP(SUBSTRING(\"TRTDAT\"::text, 2) || \r\n    LPAD(SUBSTRING(\"TRTTIM\"::text FROM 1),6,'0'),\r\n      'YYMMDDHH24MISS') - interval '7 hour')::timestamp AS time\r\n      FROM \"itm_db_ASID160448_ZTRANS0P\" \r\n      WHERE \r\n        \"TRTRTY\" = '21' AND \"TRPCCD\" = 59\r\n      GROUP BY 1\r\n)     \r\n\r\nSELECT date_trunc('second', time) as time, COUNT(*) FROM data \r\nWHERE $__timeFilter(time) GROUP BY 1 ORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "bale_db",
     "rawSql": "WITH data AS (\r\nSELECT (TO_TIMESTAMP(SUBSTRING(itm.\"TRTDAT\"::text, 2) || \r\n    LPAD(SUBSTRING(itm.\"TRTTIM\"::text FROM 1),6,'0'),\r\n      'YYMMDDHH24MISS') - interval '7 hour')::timestamp AS time, \r\n      COALESCE(rc.error_type::text, 'NA') AS error_type, \r\n      itm.\"TRTDAT\", itm.\"TRTTIM\",\r\n      itm.\"TRRSPC\",\r\n      COUNT(*) AS jumlah,\r\n      COUNT(*) FILTER(WHERE rc.error_type = 'Sukses') AS sukses,\r\n      COUNT(*) FILTER(WHERE rc.error_type = 'N') AS bisnis\r\n      FROM \"itm_db_ASID160448_ZTRANS0P\" itm LEFT JOIN response_code_dictionary rc ON  itm.\"TRRSPC\" = rc.rc AND rc.id_app_identifier = 6\r\n      WHERE itm.\"TRTRTY\" = '21' AND itm.\"TRPCCD\" = 59  \r\n      GROUP BY 1, 2, 3, 4, 5\r\n)     \r\n\r\nSELECT \r\n   (SUM(sukses) + SUM(bisnis)) / SUM(jumlah)\r\nFROM data \r\nWHERE $__timeFilter(time) \r\n\r\n"
    }
   ]
  },
  {
   "title": "Jumlah Transaksi dan Persentase Sukses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data AS (\r\nSELECT (TO_TIMESTAMP(SUBSTRING(itm.\"TRTDAT\"::text, 2) || \r\n    LPAD(SUBSTRING(itm.\"TRTTIM\"::text FROM 1),6,'0'),\r\n      'YYMMDDHH24MISS') - interval '7 hour')::timestamp AS time, \r\n      COALESCE(rc.error_type::text, 'NA') AS error_type, \r\n      itm.\"TRTDAT\", itm.\"TRTTIM\",\r\n      itm.\"TRRSPC\",\r\n      COUNT(*) AS jumlah,\r\n      COUNT(*) FILTER(WHERE rc.error_type = 'Sukses') AS sukses,\r\n      COUNT(*) FILTER(WHERE rc.error_type = 'N') AS bisnis\r\n      FROM \"itm_db_ASID160448_ZTRANS0P\" itm LEFT JOIN response_code_dictionary rc ON  itm.\"TRRSPC\" = rc.rc AND rc.id_app_identifier = 6\r\n      WHERE itm.\"TRTRTY\" = '21' AND itm.\"TRPCCD\" = 59  \r\n      GROUP BY 1, 2, 3, 4, 5\r\n)     \r\n\r\nSELECT \r\n    date_trunc('minute', time) as time_trunc,\r\n    SUM(jumlah) AS \"Jumlah Transaksi\",\r\n   (SUM(sukses) + SUM(bisnis)) / SUM(jumlah) AS \"Success Rate\"\r\nFROM data \r\nWHERE $__timeFilter(time) \r\nGROUP BY 1\r\n\r\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 61 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<h1>\n  <p style=\"font-size: 35px;\">\n    <b>QRIS ACQUIRER</b>\n  </p>\n    </h1>\n</div>"
   }
  },
  {
   "title": "Jumlah Trx",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.feature = \"qris_acquirer\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TPS ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.feature = \"qris_acquirer\"",
     "timeField": "@timestamp"
    },
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sukses",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.responseCategory:\"Success\" AND data.feature:\"qris_acquirer\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "N",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.responseCategory:\"Business Error\" AND data.feature:\"qris_acquirer\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Total Trx",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.feature:\"qris_acquirer\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Jumlah Transaksi dan Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "alias": "Sukses",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.responseCategory:\"Success\" AND data.feature:\"qris_acquirer\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "N",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.responseCategory:\"Business Error\" AND data.feature:\"qris_acquirer\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Jumlah Transaksi",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.feature:\"qris_acquirer\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 71 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n<h1>\n  <p style=\"font-size: 35px;\">\n    <b>QRIS ACQUIRER ISSUER</b>\n  </p>\n    </h1>\n</div>"
   }
  },
  {
   "title": "Jumlah Trx",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.feature = \"qris_issueracquirer\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TPS ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.feature = \"qris_issueracquirer\"",
     "timeField": "@timestamp"
    },
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sukses",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.responseCategory:\"Success\" AND data.feature:\"qris_issueracquirer\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "N",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.responseCategory:\"Business Error\" AND data.feature:\"qris_issueracquirer\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Total Trx",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.feature:\"qris_issueracquirer\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Jumlah Transaksi dan Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "alias": "Sukses",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.responseCategory:\"Success\" AND data.feature:\"qris_issueracquirer\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "N",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.responseCategory:\"Business Error\" AND data.feature:\"qris_issueracquirer\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Jumlah Transaksi",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "timeZone": "Asia/Jakarta" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "data.feature:\"qris_issueracquirer\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bale by BTN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS Last 10 Min",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 81 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT\r\n  date_trunc(\r\n    'second',\r\n    th.transaction_date - interval '7 hour'\r\n  ) as time,\r\n  count(*)\r\nFROM\r\n  bale_db_raw_bale th\r\nWHERE\r\n  th.transaction_date >= $__timeTo() :: date - interval '7 hour'\r\n  AND th.transaction_state IN ('1', '9', '8')\r\n  AND th.transaction_category IN (\r\n    'ACTIVATE_DORMANT',\r\n    'BILLPAYMENT_BANK_LOAN',\r\n    'BILLPAYMENT_BPJS_KESEHATAN',\r\n    'BILLPAYMENT_BPJS_TENAGA_KERJA',\r\n    'BILLPAYMENT_CREDIT_CARD',\r\n    'BILLPAYMENT_CREDIT_CARD_OTHER',\r\n    'BILLPAYMENT_DONATION_ACT',\r\n    'BILLPAYMENT_DONATION_BAZNAS',\r\n    'BILLPAYMENT_DONATION_DOMPET',\r\n    'BILLPAYMENT_ECOM_BUKALAPAK',\r\n    'BILLPAYMENT_ECOM_TOKOPEDIA',\r\n    'BILLPAYMENT_EDUCATION',\r\n    'BILLPAYMENT_INSURANCE',\r\n    'BILLPAYMENT_INTERNET_TV',\r\n    'BILLPAYMENT_MPN',\r\n    'BILLPAYMENT_MULTIBILLER',\r\n    'BILLPAYMENT_MULTIBILLER_LEGAL',\r\n    'BILLPAYMENT_NON_PBB',\r\n    'BILLPAYMENT_OTHER_LOAN',\r\n    'BILLPAYMENT_PBB',\r\n    'BILLPAYMENT_PDAM',\r\n    'BILLPAYMENT_PEGADAIAN',\r\n    'BILLPAYMENT_PGN',\r\n    'BILLPAYMENT_PHONE',\r\n    'BILLPAYMENT_PLN',\r\n    'BILLPAYMENT_TICKET_TRAIN',\r\n    'BILLPAYMENT_TRANSPORTATION',\r\n    'BILLPAYMENT_VA',\r\n    'BILLPAYMENT_VA_MORTGAGE',\r\n    'BILLPAYMENT_VEHICLE_TAX',\r\n    'BUY_MUTUAL_FUND',\r\n    'BUY_SBN',\r\n    'CARDLESS_DEPOSIT',\r\n    'CARDLESS_WITHDRAWAL',\r\n    'EDEPOSITO_PLACEMENT',\r\n    'FREEZE_PROXY_BIFAST',\r\n    'MONEY_CHANGER',\r\n    'PORTING_PROXY_BIFAST',\r\n    'PURCHASE_EVOUCHER_MTIX',\r\n    'PURCHASE_EVOUCHER_STREAMING',\r\n    'PURCHASE_NFC_EMONEY',\r\n    'PURCHASE_NFC_FLAZZ',\r\n    'PURCHASE_NFC_TAPCASH',\r\n    'PURCHASE_PHONE',\r\n    'PURCHASE_PLN_PREPAID',\r\n    'PURCHASE_TOPUP_DANA',\r\n    'PURCHASE_TOPUP_GOPAY',\r\n    'PURCHASE_TOPUP_ISAKU',\r\n    'PURCHASE_TOPUP_LINKAJA',\r\n    'PURCHASE_TOPUP_OVO',\r\n    'PURCHASE_TOPUP_POSPAY',\r\n    'PURCHASE_TOPUP_SHOPEEPAY',\r\n    'QR_CROSS_BORDER',\r\n    'QR_MPM',\r\n    'REGISTRATION_PROXY_BIFAST',\r\n    'SELL_MUTUAL_FUND',\r\n    'SWITCH_FROM_MUTUAL_FUND',\r\n    'SWITCH_TO_MUTUAL_FUND',\r\n    'TRANSFER_ALL',\r\n    'TRANSFER_BIFAST',\r\n    'TRANSFER_FOREX_OA',\r\n    'TRANSFER_FOREX_ON_US',\r\n    'TRANSFER_OA',\r\n    'TRANSFER_OFF_US',\r\n    'TRANSFER_ON_US',\r\n    'TRANSFER_RTGS',\r\n    'TRANSFER_SKN',\r\n    'TRANSFER_SPLIT_BILL',\r\n    'TRANSFER_SWIFT',\r\n    'UNFREEZE_PROXY_BIFAST',\r\n    'UNREGISTRATION_PROXY_BIFAST',\r\n    'UPDATE_PROXY_BIFAST'\r\n  )\r\nGROUP BY\r\n  1\r\nORDER BY\r\n  1 DESC"
      }
     ]
    },
    {
     "title": "Jumlah Transaksi Bale - All Trx",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 3, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT date_trunc('minute', th.transaction_date - interval '7 hour') AS time,\r\n  COUNT(DISTINCT th.transaction_id) AS \"Jumlah Trx Bale\"\r\nFROM raw_bale th\r\nWHERE th.transaction_state IN ('1','9','8')\r\n  AND th.transaction_category = ANY(ARRAY['ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN','BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD','BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT','BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET','BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA','BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE','BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER','BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB','BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM','BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE','BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN','BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA','BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX','BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT','CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST','MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX','PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY','PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE','PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY','PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA','PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY','PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM','REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND','SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL','TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US','TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS','TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT','UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST','UPDATE_PROXY_BIFAST'])\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 9, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT date_trunc('second', th.transaction_date  - interval '7 hour') AS time,\r\n  SUM(CASE\r\n    WHEN dc.error_type = 'Sukses' OR th.result_code IS NULL OR th.result_code = '' OR dc.error_type = 'N'\r\n    THEN 1 ELSE 0\r\n  END)::numeric / NULLIF(COUNT(DISTINCT th.transaction_id), 0) * 100 AS \"Sukses Rate\"\r\nFROM raw_bale th\r\nLEFT JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc\r\n  AND th.transaction_category = dc.jenis_transaksi\r\n  AND dc.id_app_identifier = 1\r\nWHERE th.transaction_state IN ('1','9','8')\r\n  AND th.transaction_category = ANY(ARRAY['ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN','BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD','BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT','BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET','BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA','BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE','BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER','BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB','BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM','BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE','BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN','BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA','BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX','BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT','CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST','MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX','PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY','PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE','PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY','PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA','PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY','PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM','REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND','SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL','TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US','TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS','TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT','UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST','UPDATE_PROXY_BIFAST'])\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 11, "x": 13, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT date_trunc('second', th.transaction_date  - interval '7 hour') AS time,\r\n  SUM(CASE\r\n    WHEN dc.error_type = 'Sukses' OR th.result_code IS NULL OR th.result_code = ''\r\n    THEN 1 ELSE 0\r\n  END)::numeric / NULLIF(COUNT(DISTINCT th.transaction_id), 0) * 100 AS \"Sukses\",\r\n  SUM(CASE WHEN dc.error_type = 'N' THEN 1 ELSE 0 END)::numeric\r\n  / NULLIF(COUNT(DISTINCT th.transaction_id), 0) * 100 AS \"Bisnis Error\",\r\n  SUM(CASE WHEN dc.error_type = 'S' THEN 1 ELSE 0 END)::numeric\r\n  / NULLIF(COUNT(DISTINCT th.transaction_id), 0) * 100 AS \"Sistem Error\"\r\nFROM raw_bale th\r\nLEFT JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc\r\n  AND th.transaction_category = dc.jenis_transaksi\r\n  AND dc.id_app_identifier = 1\r\nWHERE th.transaction_state IN ('1','9','8')\r\n  AND th.transaction_category = ANY(ARRAY['ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN','BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD','BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT','BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET','BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA','BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE','BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER','BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB','BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM','BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE','BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN','BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA','BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX','BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT','CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST','MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX','PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY','PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE','PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY','PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA','PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY','PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM','REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND','SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL','TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US','TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS','TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT','UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST','UPDATE_PROXY_BIFAST'])\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 145 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT date_trunc('second', th.transaction_date  - interval '7 hour') AS time,\r\n  SUM(th.transaction_amount) FILTER(WHERE dc.error_type IN ('Sukses') OR ((th.result_code IS NULL OR th.result_code = ''))) AS \"Volume Trx\",\r\n  SUM(th.transaction_amount) FILTER(WHERE dc.error_type IN ('N')) AS \"Volume Bisnis Error\",\r\n  SUM(th.transaction_amount) FILTER(WHERE dc.error_type IN ('S')) AS \"Volume Sistem Error\",\r\n  COUNT(DISTINCT th.transaction_id) FILTER(WHERE dc.error_type IN ('Sukses') OR ((th.result_code IS NULL OR th.result_code = ''))) AS \"Jumlah Sukses\",\r\n  COUNT(DISTINCT th.transaction_id) FILTER(WHERE dc.error_type IN ('N')) AS \"Jumlah Bisnis Error\",\r\n  COUNT(DISTINCT th.transaction_id) FILTER(WHERE dc.error_type IN ('S')) AS \"Jumlah Sistem Error\"\r\nFROM raw_bale th\r\nLEFT JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc\r\n  AND th.transaction_category = dc.jenis_transaksi\r\n  AND dc.id_app_identifier = 1\r\nWHERE th.transaction_state IN ('1','9','8')\r\n  AND th.transaction_category = ANY(ARRAY['ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN','BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD','BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT','BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET','BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA','BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE','BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER','BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB','BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM','BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE','BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN','BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA','BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX','BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT','CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST','MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX','PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY','PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE','PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY','PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA','PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY','PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM','REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND','SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL','TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US','TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS','TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT','UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST','UPDATE_PROXY_BIFAST'])\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Tren Transaksi - All Categories (Sukses / Gagal Bisnis / Gagal Sistem)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 9, "y": 145 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT date_trunc('minute', th.transaction_date  - interval '7 hour') AS time,\r\n  SUM(CASE WHEN dc.error_type = 'Sukses' OR th.result_code IS NULL OR th.result_code = '' THEN 1 ELSE 0 END) AS \"Sukses\",\r\n  SUM(CASE WHEN dc.error_type = 'N' THEN 1 ELSE 0 END) AS \"Gagal Bisnis\",\r\n  SUM(CASE WHEN dc.error_type = 'S' THEN 1 ELSE 0 END) AS \"Gagal Sistem\"\r\nFROM raw_bale th\r\nLEFT JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc AND th.transaction_category = dc.jenis_transaksi AND dc.id_app_identifier = 1\r\nWHERE th.transaction_state IN ('1','9','8')\r\n  AND th.transaction_category = ANY(ARRAY['ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN','BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD','BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT','BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET','BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA','BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE','BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER','BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB','BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM','BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE','BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN','BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA','BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX','BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT','CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST','MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX','PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY','PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE','PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY','PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA','PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY','PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM','REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND','SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL','TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US','TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS','TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT','UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST','UPDATE_PROXY_BIFAST'])\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1 ORDER BY 1;"
      }
     ]
    },
    {
     "title": "Top 5 Gagal Sistem",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT CONCAT(th.result_code, ' > ', th.transaction_category) AS nama_error,\r\n  COUNT(DISTINCT th.transaction_id) AS \"Sistem Error\"\r\nFROM raw_bale th\r\nINNER JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc\r\n  AND th.transaction_category = dc.jenis_transaksi\r\n  AND dc.id_app_identifier = 1\r\nWHERE th.transaction_state IN ('1','9','8')\r\n  AND th.transaction_category = ANY(ARRAY['ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN','BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD','BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT','BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET','BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA','BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE','BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER','BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB','BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM','BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE','BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN','BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA','BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX','BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT','CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST','MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX','PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY','PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE','PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY','PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA','PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY','PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM','REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND','SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL','TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US','TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS','TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT','UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST','UPDATE_PROXY_BIFAST'])\r\n  AND dc.error_type = 'S'\r\n  AND th.result_code IS NOT NULL\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Top 5 Gagal Bisnis",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT CONCAT(th.result_code, ' > ', th.transaction_category) AS nama_error,\r\n  COUNT(DISTINCT th.transaction_id) AS \"Sistem Error\"\r\nFROM raw_bale th\r\nINNER JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc\r\n  AND th.transaction_category = dc.jenis_transaksi\r\n  AND dc.id_app_identifier = 1\r\nWHERE th.transaction_state IN ('1','9','8')\r\n  AND th.transaction_category = ANY(ARRAY['ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN','BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD','BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT','BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET','BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA','BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE','BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER','BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB','BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM','BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE','BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN','BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA','BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX','BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT','CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST','MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX','PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY','PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE','PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY','PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA','PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY','PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM','REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND','SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL','TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US','TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS','TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT','UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST','UPDATE_PROXY_BIFAST'])\r\n  AND dc.error_type = 'N'\r\n  AND th.result_code IS NOT NULL\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Sample Transaksi Gagal Sistem",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH top_errors AS (\r\n  SELECT\r\n    CONCAT(th.result_code, ' > ', th.transaction_category) AS nama_error,\r\n    th.result_code,\r\n    th.transaction_category,\r\n    COUNT(*) AS total_count\r\n  FROM raw_bale th\r\n  INNER JOIN response_code_dictionary dc\r\n    ON th.result_code = dc.rc\r\n   AND th.transaction_category = dc.jenis_transaksi\r\n   AND dc.id_app_identifier = 1\r\n  WHERE dc.error_type = 'S'\r\n    AND th.transaction_state IN ('1','9','8')\r\n    AND th.transaction_category = ANY(ARRAY['ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN','BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD','BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT','BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET','BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA','BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE','BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER','BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB','BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM','BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE','BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN','BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA','BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX','BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT','CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST','MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX','PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY','PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE','PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY','PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA','PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY','PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM','REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND','SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL','TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US','TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS','TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT','UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST','UPDATE_PROXY_BIFAST'])\r\n    AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\n  GROUP BY 1,2,3\r\n  ORDER BY 4 DESC\r\n  LIMIT 5\r\n)\r\nSELECT\r\n  t.nama_error,\r\n  (rb.transaction_date - interval '7 hour')::timestamp(0) AS transaction_date,\r\n  rb.esb_ref_no,\r\n  t.total_count,\r\n  ROW_NUMBER() OVER (\r\n    PARTITION BY t.nama_error\r\n    ORDER BY rb.transaction_date DESC\r\n  ) AS rnk\r\nFROM top_errors t\r\nCROSS JOIN LATERAL (\r\n  SELECT rb.transaction_date, rb.esb_ref_no\r\n  FROM raw_bale rb\r\n  WHERE rb.result_code = t.result_code\r\n    AND rb.transaction_category = t.transaction_category\r\n    AND rb.transaction_state IN ('1','9','8')\r\n    AND rb.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND rb.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\n  ORDER BY rb.transaction_date DESC\r\n  LIMIT 5\r\n) rb;"
      }
     ]
    },
    {
     "title": "Sample Transaksi Gagal Bisnis",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH top_errors AS (\r\n  SELECT\r\n    CONCAT(th.result_code, ' > ', th.transaction_category) AS nama_error,\r\n    th.result_code,\r\n    th.transaction_category,\r\n    COUNT(*) AS total_count\r\n  FROM raw_bale th\r\n  INNER JOIN response_code_dictionary dc\r\n    ON th.result_code = dc.rc\r\n   AND th.transaction_category = dc.jenis_transaksi\r\n   AND dc.id_app_identifier = 1\r\n  WHERE dc.error_type = 'N'\r\n    AND th.transaction_state IN ('1','9','8')\r\n    AND th.transaction_category = ANY(ARRAY['ACTIVATE_DORMANT','BILLPAYMENT_BANK_LOAN','BILLPAYMENT_BPJS_KESEHATAN','BILLPAYMENT_BPJS_TENAGA_KERJA','BILLPAYMENT_CREDIT_CARD','BILLPAYMENT_CREDIT_CARD_OTHER','BILLPAYMENT_DONATION_ACT','BILLPAYMENT_DONATION_BAZNAS','BILLPAYMENT_DONATION_DOMPET','BILLPAYMENT_ECOM_BUKALAPAK','BILLPAYMENT_ECOM_TOKOPEDIA','BILLPAYMENT_EDUCATION','BILLPAYMENT_INSURANCE','BILLPAYMENT_INTERNET_TV','BILLPAYMENT_MPN','BILLPAYMENT_MULTIBILLER','BILLPAYMENT_MULTIBILLER_LEGAL','BILLPAYMENT_NON_PBB','BILLPAYMENT_OTHER_LOAN','BILLPAYMENT_PBB','BILLPAYMENT_PDAM','BILLPAYMENT_PEGADAIAN','BILLPAYMENT_PGN','BILLPAYMENT_PHONE','BILLPAYMENT_PLN','BILLPAYMENT_TICKET_TRAIN','BILLPAYMENT_TRANSPORTATION','BILLPAYMENT_VA','BILLPAYMENT_VA_MORTGAGE','BILLPAYMENT_VEHICLE_TAX','BUY_MUTUAL_FUND','BUY_SBN','CARDLESS_DEPOSIT','CARDLESS_WITHDRAWAL','EDEPOSITO_PLACEMENT','FREEZE_PROXY_BIFAST','MONEY_CHANGER','PORTING_PROXY_BIFAST','PURCHASE_EVOUCHER_MTIX','PURCHASE_EVOUCHER_STREAMING','PURCHASE_NFC_EMONEY','PURCHASE_NFC_FLAZZ','PURCHASE_NFC_TAPCASH','PURCHASE_PHONE','PURCHASE_PLN_PREPAID','PURCHASE_TOPUP_DANA','PURCHASE_TOPUP_GOPAY','PURCHASE_TOPUP_ISAKU','PURCHASE_TOPUP_LINKAJA','PURCHASE_TOPUP_OVO','PURCHASE_TOPUP_POSPAY','PURCHASE_TOPUP_SHOPEEPAY','QR_CROSS_BORDER','QR_MPM','REGISTRATION_PROXY_BIFAST','SELL_MUTUAL_FUND','SWITCH_FROM_MUTUAL_FUND','SWITCH_TO_MUTUAL_FUND','TRANSFER_ALL','TRANSFER_BIFAST','TRANSFER_FOREX_OA','TRANSFER_FOREX_ON_US','TRANSFER_OA','TRANSFER_OFF_US','TRANSFER_ON_US','TRANSFER_RTGS','TRANSFER_SKN','TRANSFER_SPLIT_BILL','TRANSFER_SWIFT','UNFREEZE_PROXY_BIFAST','UNREGISTRATION_PROXY_BIFAST','UPDATE_PROXY_BIFAST'])\r\n    AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\n  GROUP BY 1,2,3\r\n  ORDER BY 4 DESC\r\n  LIMIT 5\r\n)\r\nSELECT\r\n  t.nama_error,\r\n  (rb.transaction_date - interval '7 hour')::timestamp(0) AS transaction_date,\r\n  rb.esb_ref_no,\r\n  t.total_count,\r\n  ROW_NUMBER() OVER (\r\n    PARTITION BY t.nama_error\r\n    ORDER BY rb.transaction_date DESC\r\n  ) AS rnk\r\nFROM top_errors t\r\nCROSS JOIN LATERAL (\r\n  SELECT rb.transaction_date, rb.esb_ref_no\r\n  FROM raw_bale rb\r\n  WHERE rb.result_code = t.result_code\r\n    AND rb.transaction_category = t.transaction_category\r\n    AND rb.transaction_state IN ('1','9','8')\r\n    AND rb.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND rb.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\n  ORDER BY rb.transaction_date DESC\r\n  LIMIT 5\r\n) rb;"
      }
     ]
    }
   ]
  },
  {
   "title": "Bale Bisnis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS Last 10 Min",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2985 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT date_trunc('second', th.transaction_date) AS time,\r\n  COUNT(DISTINCT th.transaction_id) AS \"TPS\"\r\nFROM raw_bale_bisnis th\r\nWHERE th.transaction_state IN ('0','1','2','3','4')\r\n      AND th.transaction_status IN ('0','1','2','3','4')\r\n      AND th.transaction_date >= NOW() AT TIME ZONE 'Asia/Jakarta' - interval '10 minutes'\r\nGROUP BY 1\r\nORDER BY 1 DESC;"
      }
     ]
    },
    {
     "title": "Jumlah Transaksi Bale - All Trx",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 3, "y": 2985 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT date_trunc('minute', th.transaction_date) AS time,\r\n  COUNT(DISTINCT th.transaction_id) AS \"Jumlah Trx Bale Bisnis\"\r\nFROM raw_bale_bisnis th\r\nWHERE th.transaction_state IN ('0','1','2','3','4')\r\n      AND th.transaction_status IN ('0','1','2','3','4')\r\n      AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour') \r\nGROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 2985 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT date_trunc('minute', th.transaction_date) AS time,\r\n  SUM(CASE WHEN dc.error_type = 'Sukses' OR th.result_code IS NULL OR th.result_code = '' THEN 1 ELSE 0 END)::numeric / NULLIF(COUNT(DISTINCT th.transaction_id), 0) * 100 AS \"Sukses\",\r\n  SUM(CASE WHEN dc.error_type = 'N' OR th.result_code IS NULL OR th.result_code = '' THEN 1 ELSE 0 END)::numeric / NULLIF(COUNT(DISTINCT th.transaction_id), 0) * 100 AS \"Bisnis\",\r\n  SUM(CASE WHEN dc.error_type = 'S' OR th.result_code IS NULL OR th.result_code = '' THEN 1 ELSE 0 END)::numeric / NULLIF(COUNT(DISTINCT th.transaction_id), 0) * 100 AS \"Sistem\"\r\nFROM raw_bale_bisnis th\r\nLEFT JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc\r\n  AND th.transaction_category = dc.jenis_transaksi\r\n  AND dc.id_app_identifier = 2\r\nWHERE th.transaction_state IN ('0','1','2','3','4')\r\n    AND th.transaction_status IN ('0','1','2','3','4')\r\n    AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3020 },
     "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT date_trunc('second', th.transaction_date) AS time,\r\n  SUM(th.transaction_amount) FILTER(WHERE (dc.error_type IN ('Sukses') OR ((th.result_code IS NULL OR th.result_code = '')))) AS \"Volume Sukses\",\r\n  SUM(th.transaction_amount) FILTER(WHERE (dc.error_type IN ('N') OR ((th.result_code IS NULL OR th.result_code = '')))) AS \"Volume Bisnis\",\r\n  SUM(th.transaction_amount) FILTER(WHERE (dc.error_type IN ('S') OR ((th.result_code IS NULL OR th.result_code = '')))) AS \"Volume Sistem\",\r\n  COUNT(DISTINCT th.transaction_id) FILTER(WHERE (dc.error_type IN ('Sukses') OR ((th.result_code IS NULL OR th.result_code = '')))) AS \"Jumlah Sukses\",\r\n  COUNT(DISTINCT th.transaction_id) FILTER(WHERE (dc.error_type IN ('N') OR ((th.result_code IS NULL OR th.result_code = '')))) AS \"Jumlah Bisnis\",\r\n  COUNT(DISTINCT th.transaction_id) FILTER(WHERE (dc.error_type IN ('S') OR ((th.result_code IS NULL OR th.result_code = '')))) AS \"Jumlah Sistem\"\r\nFROM raw_bale_bisnis th\r\nLEFT JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc\r\n  AND th.transaction_category = dc.jenis_transaksi\r\n  AND dc.id_app_identifier = 2\r\nWHERE th.transaction_state IN ('0','1','2','3','4')\r\n  AND th.transaction_status IN ('0','1','2','3','4')\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Tren Transaksi - All Categories (Sukses / Gagal Bisnis / Gagal Sistem)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 3020 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT date_trunc('minute', th.transaction_date) AS time,\r\n  SUM(CASE WHEN dc.error_type = 'Sukses' OR th.result_code IS NULL OR th.result_code = '' THEN 1 ELSE 0 END) AS \"Sukses\",\r\n  SUM(CASE WHEN dc.error_type = 'N' THEN 1 ELSE 0 END) AS \"Gagal Bisnis\",\r\n  SUM(CASE WHEN dc.error_type = 'S' THEN 1 ELSE 0 END) AS \"Gagal Sistem\"\r\nFROM raw_bale_bisnis th\r\nLEFT JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc AND th.transaction_category = dc.jenis_transaksi AND dc.id_app_identifier = 2\r\nWHERE th.transaction_state IN ('0','1','2','3','4')\r\n    AND th.transaction_status IN ('0','1','2','3','4')\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1 ORDER BY 1;"
      }
     ]
    },
    {
     "title": "Top 5 Gagal Sistem",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3028 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT CONCAT(th.result_code, ' > ', th.transaction_category) AS nama_error,\r\n  COUNT(DISTINCT th.transaction_id) AS \"Sistem Error\"\r\nFROM raw_bale_bisnis th\r\nINNER JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc\r\n  AND th.transaction_category = dc.jenis_transaksi\r\n  AND dc.id_app_identifier = 2\r\nWHERE th.transaction_state IN ('0','1','2','3','4')\r\n    AND th.transaction_status IN ('0','1','2','3','4')\r\n  AND dc.error_type = 'S'\r\n  AND th.result_code IS NOT NULL\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Top 5 Gagal Bisnis",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3028 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "SELECT CONCAT(th.result_code, ' > ', th.transaction_category) AS nama_error,\r\n  COUNT(DISTINCT th.transaction_id) AS \"Sistem Error\"\r\nFROM raw_bale_bisnis th\r\nINNER JOIN response_code_dictionary dc\r\n  ON th.result_code = dc.rc\r\n  AND th.transaction_category = dc.jenis_transaksi\r\n  AND dc.id_app_identifier = 2\r\nWHERE th.transaction_state IN ('0','1','2','3','4')\r\n    AND th.transaction_status IN ('0','1','2','3','4')\r\n  AND dc.error_type = 'N'\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Sample Transaksi Gagal Sistem",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3036 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH top_errors AS (\r\n  SELECT CONCAT(th.result_code, ' > ', th.transaction_category) AS nama_error,\r\n    th.result_code, th.transaction_category,\r\n    COUNT(th.transaction_id) AS total_count\r\n  FROM raw_bale_bisnis th\r\n  INNER JOIN response_code_dictionary dc\r\n    ON th.result_code = dc.rc\r\n    AND th.transaction_category = dc.jenis_transaksi\r\n    AND dc.id_app_identifier = 2\r\n  WHERE dc.error_type = 'S'\r\n    AND th.transaction_state IN ('0','1','2','3','4')\r\n    AND th.transaction_status IN ('0','1','2','3','4')\r\n    AND th.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n  GROUP BY 1, 2, 3\r\n  ORDER BY 4 DESC\r\n  LIMIT 5\r\n),\r\nranked_data AS (\r\n  SELECT t.nama_error,\r\n    rb.transaction_date::timestamp(0) AS transaction_date, t.total_count,\r\n    ROW_NUMBER() OVER (PARTITION BY t.nama_error ORDER BY rb.transaction_date DESC) AS rnk\r\n  FROM raw_bale_bisnis rb\r\n  JOIN top_errors t\r\n    ON rb.result_code = t.result_code\r\n    AND rb.transaction_category = t.transaction_category\r\n  WHERE rb.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n)\r\nSELECT * FROM ranked_data WHERE rnk <= 5;\r\n\r\n"
      }
     ]
    },
    {
     "title": "Sample Transaksi Gagal Bisnis",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3036 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH top_errors AS (\r\n  SELECT CONCAT(th.result_code, ' > ', th.transaction_category) AS nama_error,\r\n    th.result_code, th.transaction_category,\r\n    COUNT(th.transaction_id) AS total_count\r\n  FROM raw_bale_bisnis th\r\n  INNER JOIN response_code_dictionary dc\r\n    ON th.result_code = dc.rc\r\n    AND th.transaction_category = dc.jenis_transaksi\r\n    AND dc.id_app_identifier = 2\r\n  WHERE dc.error_type = 'N'\r\n    AND th.transaction_state IN ('0','1','2','3','4')\r\n    AND th.transaction_status IN ('0','1','2','3','4')\r\n    AND th.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n  GROUP BY 1, 2, 3\r\n  ORDER BY 4 DESC\r\n  LIMIT 5\r\n),\r\nranked_data AS (\r\n  SELECT t.nama_error,\r\n    rb.transaction_date::timestamp(0) AS transaction_date, t.total_count,\r\n    ROW_NUMBER() OVER (PARTITION BY t.nama_error ORDER BY rb.transaction_date DESC) AS rnk\r\n  FROM raw_bale_bisnis rb\r\n  JOIN top_errors t\r\n    ON rb.result_code = t.result_code\r\n    AND rb.transaction_category = t.transaction_category\r\n  WHERE rb.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n)\r\nSELECT * FROM ranked_data WHERE rnk <= 5;\r\n\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "EDC Agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS Last 10 Min",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 198 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n  date_trunc('second', sr.transaction_date),\r\n  SUM(sr.total_transaksi) AS \"TPS\"\r\nFROM data2 sr\r\nWHERE sr.transaction_date >= NOW() AT TIME ZONE 'Asia/Jakarta' - interval '10 minutes'\r\nGROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Jumlah Transaksi Bale - All Trx",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 3, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT \r\n  date_trunc('minute', sr.transaction_date) AS time,\r\n  SUM(sr.total_transaksi) AS \"Jumlah Trx\"\r\nFROM data2 sr\r\nWHERE\r\n  $__timeFilter(sr.transaction_date)\r\n  GROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 10, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n    date_trunc('minute', sr.transaction_date) AS time,\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('Sukses', 'N') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Success Rate\"\r\nFROM data2 sr\r\nWHERE $__timeFilter(sr.transaction_date)\r\nGROUP BY 1\r\nORDER BY 1;\r\n\r\n"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 10, "x": 14, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n    date_trunc('minute', sr.transaction_date) AS time,\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('Sukses') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Sukses\",\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('N') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Bisnis\",\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('S') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Sistem\"\r\nFROM data2 sr\r\nWHERE $__timeFilter(sr.transaction_date)\r\nGROUP BY 1\r\nORDER BY 1;\r\n\r\n"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 290 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.result_code,\r\n        t.\"TRTRN$\",\r\n        t.error_type,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            tr.\"TRTRN$\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY 1, 2, 3, 4, 5, 6\r\n)\r\n\r\n\r\nSELECT date_trunc('second', th.transaction_date) AS time,\r\n  SUM(th.\"TRTRN$\") FILTER(WHERE th.error_type IN ('Sukses')) AS \"Volume Sukses\",\r\n  SUM(th.\"TRTRN$\") FILTER(WHERE th.error_type IN ('N')) AS \"Volume Bisnis Error\",\r\n  SUM(th.\"TRTRN$\") FILTER(WHERE th.error_type IN ('S')) AS \"Volume Sistem Error\",\r\n  SUM(th.total_transaksi) FILTER(WHERE th.error_type IN ('Sukses'))AS \"Jumlah Sukses\",\r\n  SUM(th.total_transaksi) FILTER(WHERE th.error_type IN ('N'))AS \"Jumlah Bisnis Error\",\r\n  SUM(th.total_transaksi) FILTER(WHERE th.error_type IN ('S'))AS \"Jumlah Sistem Error\"\r\nFROM data2 th\r\nWHERE \r\n  th.error_type IN ('Sukses')\r\n  AND $__timeFilter(th.transaction_date)\r\nGROUP BY 1\r\nORDER BY 1;\r\n\r\n-- SELECT \"TRTRN$\" FROM \"ASID160448_ZTRANS0P\" LIMIT 1"
      }
     ]
    },
    {
     "title": "Jumlah Transaksi dan Persentase Sukses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT \r\n    date_trunc('minute', sr.transaction_date ) \r\n  - (extract(minute from sr.transaction_date)::int % 3) * interval '1 minute' AS time,\r\n    SUM(sr.total_transaksi) AS total_transaksi,\r\n    (\r\n        SUM(CASE \r\n            WHEN sr.status_transaksi IN ('Sukses', 'N')\r\n            THEN sr.total_transaksi \r\n            ELSE 0 \r\n        END)::numeric\r\n        /\r\n        NULLIF(SUM(sr.total_transaksi), 0)\r\n    ) * 100 AS \"Persentase Sukses\"\r\nFROM data2 sr\r\nWHERE sr.transaction_date >= $__timeFrom()::timestamp\r\n  AND sr.transaction_date <= $__timeTo()::timestamp\r\nGROUP BY time\r\nORDER BY time;"
      }
     ]
    },
    {
     "title": "Top 5 Gagal Sistem",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n  SUM(th.total_transaksi) AS \"Sistem Error\"\r\nFROM data2 th\r\nWHERE th.error_type = 'S'\r\n  AND $__timeFilter(th.transaction_date)\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Top 5 Gagal Bisnis",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 298 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n  SUM(th.total_transaksi) AS \"Sistem Error\"\r\nFROM data2 th\r\nWHERE th.error_type = 'N'\r\n  AND $__timeFilter(th.transaction_date)\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Sample Transaksi Gagal Sistem",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 306 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRRF#\",\r\n        t.\"TRSTAN\",\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            tr.\"TRRRF#\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY 1, 2, 3, 4, 5, 6, 7\r\n), top_errors AS (\r\n  SELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n    th.result_code, th.\"TRTRTY\",\r\n    SUM(th.total_transaksi) AS total_count\r\n  FROM data2 th\r\n  WHERE th.error_type = 'S'\r\n    AND th.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n  GROUP BY 1, 2, 3\r\n  ORDER BY 4 DESC\r\n  LIMIT 5\r\n),\r\nranked_data AS (\r\n  SELECT t.nama_error,\r\n    rb.transaction_date::timestamp(0) AS transaction_date,\r\n    rb.\"TRSTAN\", rb.\"TRRRF#\", t.total_count,\r\n    ROW_NUMBER() OVER (PARTITION BY t.nama_error ORDER BY rb.transaction_date DESC) AS rnk\r\n  FROM data2 rb\r\n  JOIN top_errors t\r\n    ON rb.result_code = t.result_code\r\n    AND rb.\"TRTRTY\" = t.\"TRTRTY\"\r\n  WHERE rb.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n)\r\n\r\nSELECT * FROM ranked_data WHERE rnk <= 5;\r\n--  SELECT * FROM \"ASID160448_ZTRANS0P\" LIMIT 1"
      }
     ]
    },
    {
     "title": "Sample Transaksi Gagal Bisnis",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 306 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRRF#\",\r\n        t.\"TRSTAN\",\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            tr.\"TRRRF#\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 7\r\n        WHERE\r\n            tr.\"TRTRTY\" NOT IN ('21','6A','6B','C1','C2')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY 1, 2, 3, 4, 5, 6, 7\r\n), top_errors AS (\r\n  SELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n    th.result_code, th.\"TRTRTY\",\r\n    SUM(th.total_transaksi) AS total_count\r\n  FROM data2 th\r\n  WHERE th.error_type = 'N'\r\n    AND th.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n  GROUP BY 1, 2, 3\r\n  ORDER BY 4 DESC\r\n  LIMIT 5\r\n),\r\nranked_data AS (\r\n  SELECT t.nama_error,\r\n    rb.transaction_date::timestamp(0) AS transaction_date,\r\n    rb.\"TRSTAN\", rb.\"TRRRF#\", t.total_count,\r\n    ROW_NUMBER() OVER (PARTITION BY t.nama_error ORDER BY rb.transaction_date DESC) AS rnk\r\n  FROM data2 rb\r\n  JOIN top_errors t\r\n    ON rb.result_code = t.result_code\r\n    AND rb.\"TRTRTY\" = t.\"TRTRTY\"\r\n  WHERE rb.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n)\r\n\r\nSELECT * FROM ranked_data WHERE rnk <= 5;\r\n--  SELECT * FROM \"ASID160448_ZTRANS0P\" LIMIT 1"
      }
     ]
    }
   ]
  },
  {
   "title": "EDC Merchant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS Last 10 Min",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 84 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n         LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n  date_trunc('second', sr.transaction_date),\r\n  SUM(sr.total_transaksi) AS \"TPS\"\r\nFROM data2 sr\r\nWHERE sr.transaction_date >= NOW() AT TIME ZONE 'Asia/Jakarta' - interval '10 minutes'\r\nGROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Jumlah Transaksi Bale - All Trx",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 3, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n         LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT \r\n  date_trunc('minute', sr.transaction_date) AS time,\r\n  SUM(sr.total_transaksi) AS \"Jumlah Trx\"\r\nFROM data2 sr\r\nWHERE\r\n  $__timeFilter(sr.transaction_date)\r\n  GROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 11, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n         LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n    date_trunc('minute', sr.transaction_date) AS time,\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('Sukses', 'N') THEN sr.total_transaksi ELSE 0 END)::numeric/NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Success Rate\"\r\nFROM data2 sr\r\nWHERE $__timeFilter(sr.transaction_date)\r\nGROUP BY 1\r\nORDER BY 1;\r\n\r\n"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n         LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n    date_trunc('minute', sr.transaction_date) AS time,\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('Sukses') THEN sr.total_transaksi ELSE 0 END)::numeric/NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Sukses\",\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('N') THEN sr.total_transaksi ELSE 0 END)::numeric/NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Bisnis\",\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('S') THEN sr.total_transaksi ELSE 0 END)::numeric/NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Sistem\"\r\nFROM data2 sr\r\nWHERE $__timeFilter(sr.transaction_date)\r\nGROUP BY 1\r\nORDER BY 1;\r\n\r\n"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 120 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.result_code,\r\n        t.\"TRTRN$\",\r\n        t.error_type,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            tr.\"TRTRN$\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n         LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY 1, 2, 3, 4, 5, 6\r\n)\r\n\r\n\r\nSELECT date_trunc('second', th.transaction_date) AS time,\r\n  SUM(th.\"TRTRN$\") FILTER(WHERE th.error_type IN ('Sukses')) AS \"Volume Sukses\",\r\n  SUM(th.\"TRTRN$\") FILTER(WHERE th.error_type IN ('N')) AS \"Volume Bisnis Error\",\r\n  SUM(th.\"TRTRN$\") FILTER(WHERE th.error_type IN ('S')) AS \"Volume Sistem Error\",\r\n  SUM(th.total_transaksi) FILTER(WHERE th.error_type IN ('Sukses'))AS \"Jumlah Sukses\",\r\n  SUM(th.total_transaksi) FILTER(WHERE th.error_type IN ('N'))AS \"Jumlah Bisnis Error\",\r\n  SUM(th.total_transaksi) FILTER(WHERE th.error_type IN ('S'))AS \"Jumlah Sistem Error\"\r\nFROM data2 th\r\nWHERE \r\n  th.error_type IN ('Sukses')\r\n  AND $__timeFilter(th.transaction_date)\r\nGROUP BY 1\r\nORDER BY 1;\r\n\r\n-- SELECT \"TRTRN$\" FROM \"ASID160448_ZTRANS0P\" LIMIT 1"
      }
     ]
    },
    {
     "title": "Jumlah Transaksi dan Persentase Sukses",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND dc.id_app_identifier = 6\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT \r\n    date_trunc('minute', sr.transaction_date) \r\n  - (extract(minute from sr.transaction_date)::int % 3) * interval '1 minute' AS time,\r\n    SUM(sr.total_transaksi) AS total_transaksi,\r\n    (\r\n        SUM(CASE \r\n            WHEN sr.status_transaksi IN ('Sukses', 'N')\r\n            THEN sr.total_transaksi \r\n            ELSE 0 \r\n        END)::numeric\r\n        /\r\n        NULLIF(SUM(sr.total_transaksi), 0)\r\n    ) * 100 AS \"Persentase Sukses\"\r\nFROM data2 sr\r\n-- JOIN app_identifier ai\r\n--   ON bl.id_app_identifier = ai.id\r\nWHERE $__timeFilter(sr.transaction_date)\r\nGROUP BY time\r\nORDER BY time;"
      }
     ]
    },
    {
     "title": "Top 5 Gagal Sistem",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n         LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n  SUM(th.total_transaksi) AS \"Sistem Error\"\r\nFROM data2 th\r\nWHERE th.error_type = 'S'\r\n  AND $__timeFilter(th.transaction_date)\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Top 5 Gagal Bisnis",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n  SUM(th.total_transaksi) AS \"Sistem Error\"\r\nFROM data2 th\r\nWHERE th.error_type = 'N'\r\n  AND $__timeFilter(th.transaction_date)\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Sample Transaksi Gagal Sistem",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRRF#\",\r\n        t.\"TRSTAN\",\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            tr.\"TRRRF#\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n         LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY 1, 2, 3, 4, 5, 6, 7\r\n), top_errors AS (\r\n  SELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n    th.result_code, th.\"TRTRTY\",\r\n    SUM(th.total_transaksi) AS total_count\r\n  FROM data2 th\r\n  WHERE th.error_type = 'S'\r\n    AND th.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n  GROUP BY 1, 2, 3\r\n  ORDER BY 4 DESC\r\n  LIMIT 5\r\n),\r\nranked_data AS (\r\n  SELECT t.nama_error,\r\n    rb.transaction_date::timestamp(0) AS transaction_date,\r\n    rb.\"TRSTAN\", rb.\"TRRRF#\", t.total_count,\r\n    ROW_NUMBER() OVER (PARTITION BY t.nama_error ORDER BY rb.transaction_date DESC) AS rnk\r\n  FROM data2 rb\r\n  JOIN top_errors t\r\n    ON rb.result_code = t.result_code\r\n    AND rb.\"TRTRTY\" = t.\"TRTRTY\"\r\n  WHERE rb.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n)\r\n\r\nSELECT * FROM ranked_data WHERE rnk <= 5;\r\n--  SELECT * FROM \"ASID160448_ZTRANS0P\" LIMIT 1"
      }
     ]
    },
    {
     "title": "Sample Transaksi Gagal Bisnis",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRRF#\",\r\n        t.\"TRSTAN\",\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            tr.\"TRRRF#\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n         LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc AND dc.id_app_identifier = 6\r\n        WHERE\r\n            tr.\"TRTRTY\" IN ('21')\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n    ) t\r\n    GROUP BY 1, 2, 3, 4, 5, 6, 7\r\n), top_errors AS (\r\n  SELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n    th.result_code, th.\"TRTRTY\",\r\n    SUM(th.total_transaksi) AS total_count\r\n  FROM data2 th\r\n  WHERE th.error_type = 'N'\r\n    AND th.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n  GROUP BY 1, 2, 3\r\n  ORDER BY 4 DESC\r\n  LIMIT 5\r\n),\r\nranked_data AS (\r\n  SELECT t.nama_error,\r\n    rb.transaction_date::timestamp(0) AS transaction_date,\r\n    rb.\"TRSTAN\", rb.\"TRRRF#\", t.total_count,\r\n    ROW_NUMBER() OVER (PARTITION BY t.nama_error ORDER BY rb.transaction_date DESC) AS rnk\r\n  FROM data2 rb\r\n  JOIN top_errors t\r\n    ON rb.result_code = t.result_code\r\n    AND rb.\"TRTRTY\" = t.\"TRTRTY\"\r\n  WHERE rb.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n)\r\n\r\nSELECT * FROM ranked_data WHERE rnk <= 5;\r\n--  SELECT * FROM \"ASID160448_ZTRANS0P\" LIMIT 1"
      }
     ]
    }
   ]
  },
  {
   "title": "EDC Merchant Ancol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS Last 10 Min",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 85 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n  date_trunc('second', sr.transaction_date),\r\n  SUM(sr.total_transaksi) AS \"TPS\"\r\nFROM data2 sr\r\nWHERE sr.transaction_date >= NOW() AT TIME ZONE 'Asia/Jakarta' - interval '10 minutes'\r\nGROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Jumlah Transaksi Bale - All Trx",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 3, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT \r\n  date_trunc('minute', sr.transaction_date) AS time,\r\n  SUM(sr.total_transaksi) AS \"Jumlah Trx\"\r\nFROM data2 sr\r\nWHERE\r\n  $__timeFilter(sr.transaction_date)\r\n  GROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 11, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n    date_trunc('minute', sr.transaction_date) AS time,\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('Sukses', 'N') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Success Rate\"\r\nFROM data2 sr\r\nWHERE $__timeFilter(sr.transaction_date)\r\nGROUP BY 1\r\nORDER BY 1;\r\n\r\n"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n    date_trunc('minute', sr.transaction_date) AS time,\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('Sukses') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Sukses\",\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('N') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Bisnis\",\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('S') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Sistem\"\r\nFROM data2 sr\r\nWHERE $__timeFilter(sr.transaction_date)\r\nGROUP BY 1\r\nORDER BY 1;\r\n\r\n"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.result_code,\r\n        t.error_type,\r\n        t.\"TRTRN$\",\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            tr.\"TRTRN$\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.result_code,\r\n        t.\"TRRSPC\",\r\n        t.\"TRTRN$\",\r\n        t.error_type\r\n)\r\n\r\nSELECT \r\n  date_trunc('minute', sr.transaction_date) AS time,\r\n  SUM(sr.\"TRTRN$\") FILTER(WHERE sr.error_type IN ('Sukses')) AS \"Volume Sukses\",\r\n  SUM(sr.\"TRTRN$\") FILTER(WHERE sr.error_type IN ('N')) AS \"Volume Bisnis Error\",\r\n  SUM(sr.\"TRTRN$\") FILTER(WHERE sr.error_type IN ('S')) AS \"Volume Sistem Error\",\r\n  SUM(sr.total_transaksi) FILTER(WHERE sr.error_type IN ('Sukses'))AS \"Jumlah Sukses\",\r\n  SUM(sr.total_transaksi) FILTER(WHERE sr.error_type IN ('N'))AS \"Jumlah Bisnis Error\",\r\n  SUM(sr.total_transaksi) FILTER(WHERE sr.error_type IN ('S'))AS \"Jumlah Sistem Error\"\r\nFROM data2 sr\r\nWHERE\r\n  $__timeFilter(sr.transaction_date) AND sr.error_type = 'Sukses'\r\n  GROUP BY 1\r\nORDER BY 1;"
      }
     ]
    },
    {
     "title": "Jumlah Transaksi dan Persentase Sukses",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n            AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\n\r\nSELECT \r\n    date_trunc('minute', sr.transaction_date) \r\n  - (extract(minute from sr.transaction_date)::int % 3) * interval '1 minute' AS time,\r\n    SUM(sr.total_transaksi) AS total_transaksi,\r\n    (\r\n        SUM(CASE \r\n            WHEN sr.status_transaksi IN ('Sukses', 'N')\r\n            THEN sr.total_transaksi \r\n            ELSE 0 \r\n        END)::numeric\r\n        /\r\n        NULLIF(SUM(sr.total_transaksi), 0)\r\n    ) * 100 AS \"Persentase Sukses\"\r\nFROM data2 sr\r\nWHERE $__timeFilter(sr.transaction_date)\r\nGROUP BY time\r\nORDER BY time;"
      }
     ]
    },
    {
     "title": "Top 5 Gagal Sistem",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n  SUM(th.total_transaksi) AS \"Sistem Error\"\r\nFROM data2 th\r\nWHERE th.error_type = 'S'\r\n  AND $__timeFilter(th.transaction_date)\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Top 5 Gagal Bisnis",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n  SUM(th.total_transaksi) AS \"Sistem Error\"\r\nFROM data2 th\r\nWHERE th.error_type = 'N'\r\n  AND $__timeFilter(th.transaction_date)\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Sample Transaksi Gagal Sistem",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRRF#\",\r\n        t.\"TRSTAN\",\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            tr.\"TRRRF#\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY 1, 2, 3, 4, 5, 6, 7\r\n), top_errors AS (\r\n  SELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n    th.result_code, th.\"TRTRTY\",\r\n    SUM(th.total_transaksi) AS total_count\r\n  FROM data2 th\r\n  WHERE th.error_type = 'S'\r\n    AND th.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n  GROUP BY 1, 2, 3\r\n  ORDER BY 4 DESC\r\n  LIMIT 5\r\n),\r\nranked_data AS (\r\n  SELECT t.nama_error,\r\n    rb.transaction_date::timestamp(0) AS transaction_date,\r\n    rb.\"TRSTAN\", rb.\"TRRRF#\", t.total_count,\r\n    ROW_NUMBER() OVER (PARTITION BY t.nama_error ORDER BY rb.transaction_date DESC) AS rnk\r\n  FROM data2 rb\r\n  JOIN top_errors t\r\n    ON rb.result_code = t.result_code\r\n    AND rb.\"TRTRTY\" = t.\"TRTRTY\"\r\n  WHERE rb.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n)\r\n\r\nSELECT * FROM ranked_data WHERE rnk <= 5;\r\n--  SELECT * FROM \"ASID160448_ZTRANS0P\" LIMIT 1"
      }
     ]
    },
    {
     "title": "Sample Transaksi Gagal Bisnis",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "dataset": "dbs_db",
       "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRRF#\",\r\n        t.\"TRSTAN\",\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            tr.\"TRRRF#\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY 1, 2, 3, 4, 5, 6, 7\r\n), top_errors AS (\r\n  SELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n    th.result_code, th.\"TRTRTY\",\r\n    SUM(th.total_transaksi) AS total_count\r\n  FROM data2 th\r\n  WHERE th.error_type = 'N'\r\n    AND th.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n  GROUP BY 1, 2, 3\r\n  ORDER BY 4 DESC\r\n  LIMIT 5\r\n),\r\nranked_data AS (\r\n  SELECT t.nama_error,\r\n    rb.transaction_date::timestamp(0) AS transaction_date,\r\n    rb.\"TRSTAN\", rb.\"TRRRF#\", t.total_count,\r\n    ROW_NUMBER() OVER (PARTITION BY t.nama_error ORDER BY rb.transaction_date DESC) AS rnk\r\n  FROM data2 rb\r\n  JOIN top_errors t\r\n    ON rb.result_code = t.result_code\r\n    AND rb.\"TRTRTY\" = t.\"TRTRTY\"\r\n  WHERE rb.transaction_date BETWEEN $__timeFrom()::timestamp AND $__timeTo()::timestamp\r\n)\r\n\r\nSELECT * FROM ranked_data WHERE rnk <= 5;\r\n--  SELECT * FROM \"ASID160448_ZTRANS0P\" LIMIT 1"
      }
     ]
    }
   ]
  }
 ]
}