{
 "title": "Dashboard EDC Merchant Ancol DGOD",
 "tags": [ "DGOD" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "panels": [
  { "title": "All Trx Type/Category", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS Last 10 Min",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n  date_trunc('second', sr.transaction_date),\r\n  SUM(sr.total_transaksi) AS \"TPS\"\r\nFROM data2 sr\r\nWHERE sr.transaction_date BETWEEN ($__timeFrom()::timestamp + interval '7 hour') AND ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Jumlah Transaksi Bale - All Trx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT \r\n  date_trunc('minute', sr.transaction_date) AS time,\r\n  SUM(sr.total_transaksi) AS \"Jumlah Trx\"\r\nFROM data2 sr\r\nWHERE\r\n  sr.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND sr.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\n  GROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type AS status_transaksi\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.status_transaksi,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT\r\n    date_trunc('minute', sr.transaction_date) AS time,\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('Sukses') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Sukses\",\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('N') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Bisnis\",\r\n    (SUM(CASE WHEN sr.status_transaksi IN ('S') THEN sr.total_transaksi ELSE 0 END)::numeric / NULLIF(SUM(sr.total_transaksi),0)) * 100 AS \"Sistem\"\r\nFROM data2 sr\r\nWHERE sr.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND sr.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 1;\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.result_code,\r\n        t.error_type,\r\n        t.\"TRTRN$\",\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            tr.\"TRTRN$\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.result_code,\r\n        t.\"TRRSPC\",\r\n        t.\"TRTRN$\",\r\n        t.error_type\r\n)\r\n\r\nSELECT \r\n  date_trunc('minute', sr.transaction_date) AS time,\r\n  SUM(sr.\"TRTRN$\") FILTER(WHERE sr.error_type IN ('Sukses')) AS \"Volume Sukses\",\r\n  SUM(sr.\"TRTRN$\") FILTER(WHERE sr.error_type IN ('N')) AS \"Volume Bisnis Error\",\r\n  SUM(sr.\"TRTRN$\") FILTER(WHERE sr.error_type IN ('S')) AS \"Volume Sistem Error\",\r\n  SUM(sr.total_transaksi) FILTER(WHERE sr.error_type IN ('Sukses'))AS \"Jumlah Sukses\",\r\n  SUM(sr.total_transaksi) FILTER(WHERE sr.error_type IN ('N'))AS \"Jumlah Bisnis Error\",\r\n  SUM(sr.total_transaksi) FILTER(WHERE sr.error_type IN ('S'))AS \"Jumlah Sistem Error\"\r\nFROM data2 sr\r\nWHERE\r\n  sr.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND sr.transaction_date <= ($__timeTo()::timestamp + interval '7 hour') AND sr.error_type = 'Sukses'\r\n  GROUP BY 1\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Tren Transaksi - All Categories (Sukses / Gagal Bisnis / Gagal Sistem)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 7 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT date_trunc('minute', th.transaction_date) AS time,\r\n  SUM(CASE WHEN th.error_type = 'Sukses' OR th.result_code IS NULL OR th.result_code = '' THEN 1 ELSE 0 END) AS \"Sukses\",\r\n  SUM(CASE WHEN th.error_type = 'N' THEN 1 ELSE 0 END) AS \"Gagal Bisnis\",\r\n  SUM(CASE WHEN th.error_type = 'S' THEN 1 ELSE 0 END) AS \"Gagal Sistem\"\r\nFROM data2 th\r\nWHERE th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Top 5 Gagal Sistem",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n  SUM(th.total_transaksi) AS \"Sistem Error\"\r\nFROM data2 th\r\nWHERE th.error_type = 'S'\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Top 5 Gagal Bisnis",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH data2 AS (\r\n    SELECT\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.\"TRRSPC\",\r\n        t.error_type,\r\n        t.result_code,\r\n        COUNT(DISTINCT t.\"TRSTAN\") AS total_transaksi\r\n    FROM (\r\n        SELECT\r\n            TO_TIMESTAMP(\r\n                SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n                LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n                'YYMMDDHH24MISS'\r\n            ) AS transaction_date,\r\n            tr.\"TRRSPC\" AS result_code,\r\n            r.\"RSSHTD\" AS rc_description,\r\n            tr.\"TRRSPC\",\r\n            tr.\"TRSTAN\",\r\n            tr.\"TRTRTY\",\r\n            dc.error_type\r\n        FROM \"ASID160448_ZTRANS0P\" tr\r\n        JOIN \"ASID160448_ZRSPCD0P\" r\r\n            ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n        LEFT JOIN response_code_dictionary dc\r\n            ON tr.\"TRRSPC\"::text = dc.rc\r\n             AND dc.id_app_identifier = 61\r\n        WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n    ) t\r\n    GROUP BY\r\n        t.transaction_date,\r\n        t.\"TRTRTY\",\r\n        t.error_type,\r\n        t.result_code,\r\n        t.\"TRRSPC\"\r\n)\r\n\r\nSELECT CONCAT(th.result_code, ' > ', th.\"TRTRTY\") AS nama_error,\r\n  SUM(th.total_transaksi) AS \"Sistem Error\"\r\nFROM data2 th\r\nWHERE th.error_type = 'N'\r\n  AND th.transaction_date >= ($__timeFrom()::timestamp + interval '7 hour') AND th.transaction_date <= ($__timeTo()::timestamp + interval '7 hour')\r\nGROUP BY 1\r\nORDER BY 2 DESC\r\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Sample Transaksi Gagal Sistem",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH base AS (\r\n    SELECT\r\n        TO_TIMESTAMP(\r\n            SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n            LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n            'YYMMDDHH24MISS'\r\n        ) AS transaction_date,\r\n        tr.\"TRRSPC\" AS result_code,\r\n        tr.\"TRTRTY\",\r\n        tr.\"TRSTAN\",\r\n        tr.\"TRRRF#\",\r\n        dc.rc_description,\r\n        dc.error_type\r\n    FROM \"ASID160448_ZTRANS0P\" tr\r\n    JOIN \"ASID160448_ZRSPCD0P\" r\r\n        ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n    LEFT JOIN response_code_dictionary dc\r\n        ON tr.\"TRRSPC\"::text = dc.rc\r\n        AND dc.id_app_identifier = 61\r\n    WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND dc.error_type = 'S'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n),\r\n\r\ntop_errors AS (\r\n    SELECT\r\n        result_code,\r\n        \"TRTRTY\",\r\n        COUNT(*) AS total_count\r\n    FROM base\r\n    WHERE transaction_date BETWEEN $__timeFrom() AND $__timeTo()\r\n    GROUP BY 1,2\r\n    ORDER BY total_count DESC\r\n    LIMIT 5\r\n),\r\n\r\nranked AS (\r\n    SELECT\r\n        CONCAT(b.result_code, ' > ', b.\"TRTRTY\") AS nama_error,\r\n        b.*,\r\n        ROW_NUMBER() OVER (\r\n            PARTITION BY b.result_code, b.\"TRTRTY\"\r\n            ORDER BY b.transaction_date DESC\r\n        ) AS rnk\r\n    FROM base b\r\n    JOIN top_errors t\r\n        ON b.result_code = t.result_code\r\n        AND b.\"TRTRTY\" = t.\"TRTRTY\"\r\n)\r\n\r\nSELECT *\r\nFROM ranked\r\nWHERE rnk <= 5;"
    }
   ]
  },
  {
   "title": "Sample Transaksi Gagal Bisnis",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "dataset": "dbs_db",
     "rawSql": "WITH base AS (\r\n    SELECT\r\n        TO_TIMESTAMP(\r\n            SUBSTRING(tr.\"TRXMDT\"::text FROM 2) ||\r\n            LPAD(SUBSTRING(tr.\"TRXMTM\"::text FROM 1),6,'0'),\r\n            'YYMMDDHH24MISS'\r\n        ) AS transaction_date,\r\n        tr.\"TRRSPC\" AS result_code,\r\n        tr.\"TRTRTY\",\r\n        tr.\"TRSTAN\",\r\n        tr.\"TRRRF#\",\r\n        dc.rc_description,\r\n        dc.error_type\r\n    FROM \"ASID160448_ZTRANS0P\" tr\r\n    JOIN \"ASID160448_ZRSPCD0P\" r\r\n        ON tr.\"TRRSPC\" = r.\"RSRSPC\"\r\n    LEFT JOIN response_code_dictionary dc\r\n        ON tr.\"TRRSPC\"::text = dc.rc\r\n        AND dc.id_app_identifier = 61\r\n    WHERE\r\n            tr.\"TRTRTY\" = '21'\r\n            AND dc.error_type = 'N'\r\n            AND tr.\"TRPROD\" = 'POS'\r\n            AND dc.error_type IS NOT NULL\r\n            AND \"TRCAID\" IN (\r\n            '200719398140682',\r\n            '200719389813135',\r\n            '200719389808836',\r\n            '200719389810345',\r\n            '200719389819715',\r\n            '200719389812202',\r\n            '200719389815991',\r\n            '200719389809769',\r\n            '200719389811278',\r\n            '200719392283028',\r\n            '200719392284951',\r\n            '200719392281161',\r\n            '200719392293973',\r\n            '200719392300602',\r\n            '200719392299553',\r\n            '200719389824014',\r\n            '200719389830246',\r\n            '200719389828737',\r\n            '200719392280238',\r\n            '200719392277795',\r\n            '200719389823080',\r\n            '200719389827804',\r\n            '200719392276862',\r\n            '200719389829660',\r\n            '200719392297696',\r\n            '200719392298620',\r\n            '200719389825947',\r\n            '200719389826870',\r\n            '200719392286818',\r\n            '200719392279652',\r\n            '200719392295830',\r\n            '200719392294907',\r\n            '200719392296763',\r\n            '200719392285884',\r\n            '200719389831179',\r\n            '200719392278729',\r\n            '200719392301535',\r\n            '200719389801323',\r\n            '200719389800399',\r\n            '200719389822157',\r\n            '200719392271216',\r\n            '200719392273072',\r\n            '200719392274006',\r\n            '200719389821224',\r\n            '200719392272149',\r\n            '200719389820290',\r\n            '200719392275939',\r\n            '160016154115765',\r\n            '160016154115772',\r\n            '160016154115777',\r\n            '160016154115778',\r\n            '160016154115780',\r\n            '160016154115781',\r\n            '160016154115783',\r\n            '160016154115785',\r\n            '160016154115773',\r\n            '160016154115775',\r\n            '160016154115774',\r\n            '160016154115776',\r\n            '160016154115771',\r\n            '160016154115779',\r\n            '160016154115770',\r\n            '160016154115782',\r\n            '160016154115769',\r\n            '160016154115766',\r\n            '160016154115767',\r\n            '160016154115768',\r\n            '160016154115784',\r\n            '160016154115786',\r\n            '160016154115787',\r\n            '160016154115788',\r\n            '160016154115789',\r\n            '160016154115790',\r\n            '160016154115791',\r\n            '160016154115792',\r\n            '160016158125758',\r\n            '160016158125731',\r\n            '160016158125759',\r\n            '160016154115764',\r\n            '160016158125760',\r\n            '160016158125761',\r\n            '160016158125762',\r\n            '160016158125763'\r\n            )\r\n),\r\n\r\ntop_errors AS (\r\n    SELECT\r\n        result_code,\r\n        \"TRTRTY\",\r\n        COUNT(*) AS total_count\r\n    FROM base\r\n    WHERE transaction_date BETWEEN $__timeFrom() AND $__timeTo()\r\n    GROUP BY 1,2\r\n    ORDER BY total_count DESC\r\n    LIMIT 5\r\n),\r\n\r\nranked AS (\r\n    SELECT\r\n        CONCAT(b.result_code, ' > ', b.\"TRTRTY\") AS nama_error,\r\n        b.*,\r\n        ROW_NUMBER() OVER (\r\n            PARTITION BY b.result_code, b.\"TRTRTY\"\r\n            ORDER BY b.transaction_date DESC\r\n        ) AS rnk\r\n    FROM base b\r\n    JOIN top_errors t\r\n        ON b.result_code = t.result_code\r\n        AND b.\"TRTRTY\" = t.\"TRTRTY\"\r\n)\r\n\r\nSELECT *\r\nFROM ranked\r\nWHERE rnk <= 5;"
    }
   ]
  }
 ]
}