/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserApprovalRouteImport } from './routes/user-approval'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadSuccessRateRouteImport } from './routes/api/upload-success-rate'
import { Route as ApiUploadDictionaryRouteImport } from './routes/api/upload-dictionary'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiProcessingProcessManualRouteImport } from './routes/api/processing/process-manual'
import { Route as ApiBaleProcessManualRouteImport } from './routes/api/bale/process-manual'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UserApprovalRoute = UserApprovalRouteImport.update({
  id: '/user-approval',
  path: '/user-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadSuccessRateRoute = ApiUploadSuccessRateRouteImport.update({
  id: '/api/upload-success-rate',
  path: '/api/upload-success-rate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadDictionaryRoute = ApiUploadDictionaryRouteImport.update({
  id: '/api/upload-dictionary',
  path: '/api/upload-dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessingProcessManualRoute =
  ApiProcessingProcessManualRouteImport.update({
    id: '/api/processing/process-manual',
    path: '/api/processing/process-manual',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBaleProcessManualRoute = ApiBaleProcessManualRouteImport.update({
  id: '/api/bale/process-manual',
  path: '/api/bale/process-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRoute
  '/user-approval': typeof UserApprovalRoute
  '/api/upload-dictionary': typeof ApiUploadDictionaryRoute
  '/api/upload-success-rate': typeof ApiUploadSuccessRateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bale/process-manual': typeof ApiBaleProcessManualRoute
  '/api/processing/process-manual': typeof ApiProcessingProcessManualRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRoute
  '/user-approval': typeof UserApprovalRoute
  '/api/upload-dictionary': typeof ApiUploadDictionaryRoute
  '/api/upload-success-rate': typeof ApiUploadSuccessRateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bale/process-manual': typeof ApiBaleProcessManualRoute
  '/api/processing/process-manual': typeof ApiProcessingProcessManualRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/superadmin': typeof SuperadminRoute
  '/user-approval': typeof UserApprovalRoute
  '/api/upload-dictionary': typeof ApiUploadDictionaryRoute
  '/api/upload-success-rate': typeof ApiUploadSuccessRateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bale/process-manual': typeof ApiBaleProcessManualRoute
  '/api/processing/process-manual': typeof ApiProcessingProcessManualRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/login'
    | '/register'
    | '/superadmin'
    | '/user-approval'
    | '/api/upload-dictionary'
    | '/api/upload-success-rate'
    | '/api/auth/$'
    | '/api/bale/process-manual'
    | '/api/processing/process-manual'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/login'
    | '/register'
    | '/superadmin'
    | '/user-approval'
    | '/api/upload-dictionary'
    | '/api/upload-success-rate'
    | '/api/auth/$'
    | '/api/bale/process-manual'
    | '/api/processing/process-manual'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/login'
    | '/register'
    | '/superadmin'
    | '/user-approval'
    | '/api/upload-dictionary'
    | '/api/upload-success-rate'
    | '/api/auth/$'
    | '/api/bale/process-manual'
    | '/api/processing/process-manual'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SuperadminRoute: typeof SuperadminRoute
  UserApprovalRoute: typeof UserApprovalRoute
  ApiUploadDictionaryRoute: typeof ApiUploadDictionaryRoute
  ApiUploadSuccessRateRoute: typeof ApiUploadSuccessRateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBaleProcessManualRoute: typeof ApiBaleProcessManualRoute
  ApiProcessingProcessManualRoute: typeof ApiProcessingProcessManualRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-approval': {
      id: '/user-approval'
      path: '/user-approval'
      fullPath: '/user-approval'
      preLoaderRoute: typeof UserApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-success-rate': {
      id: '/api/upload-success-rate'
      path: '/api/upload-success-rate'
      fullPath: '/api/upload-success-rate'
      preLoaderRoute: typeof ApiUploadSuccessRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-dictionary': {
      id: '/api/upload-dictionary'
      path: '/api/upload-dictionary'
      fullPath: '/api/upload-dictionary'
      preLoaderRoute: typeof ApiUploadDictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/processing/process-manual': {
      id: '/api/processing/process-manual'
      path: '/api/processing/process-manual'
      fullPath: '/api/processing/process-manual'
      preLoaderRoute: typeof ApiProcessingProcessManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bale/process-manual': {
      id: '/api/bale/process-manual'
      path: '/api/bale/process-manual'
      fullPath: '/api/bale/process-manual'
      preLoaderRoute: typeof ApiBaleProcessManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SuperadminRoute: SuperadminRoute,
  UserApprovalRoute: UserApprovalRoute,
  ApiUploadDictionaryRoute: ApiUploadDictionaryRoute,
  ApiUploadSuccessRateRoute: ApiUploadSuccessRateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBaleProcessManualRoute: ApiBaleProcessManualRoute,
  ApiProcessingProcessManualRoute: ApiProcessingProcessManualRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
