/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardUploadsRouteImport } from './routes/_dashboard/uploads'
import { Route as DashboardUnmappedRcRouteImport } from './routes/_dashboard/unmapped-rc'
import { Route as DashboardTransactionsRouteImport } from './routes/_dashboard/transactions'
import { Route as DashboardDocsRouteImport } from './routes/_dashboard/docs'
import { Route as DashboardDictionaryRouteImport } from './routes/_dashboard/dictionary'
import { Route as DashboardApplicationRouteImport } from './routes/_dashboard/application'
import { Route as DashboardSuperadminIndexRouteImport } from './routes/_dashboard/superadmin/index'
import { Route as DashboardDocsIndexRouteImport } from './routes/_dashboard/docs/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardSuperadminUsersRouteImport } from './routes/_dashboard/superadmin/users'
import { Route as DashboardSuperadminSchedulerRouteImport } from './routes/_dashboard/superadmin/scheduler'
import { Route as DashboardSuperadminProcessingRouteImport } from './routes/_dashboard/superadmin/processing'
import { Route as DashboardSuperadminJobsRouteImport } from './routes/_dashboard/superadmin/jobs'
import { Route as DashboardSuperadminHousekeepingRouteImport } from './routes/_dashboard/superadmin/housekeeping'
import { Route as DashboardSuperadminConfigRouteImport } from './routes/_dashboard/superadmin/config'
import { Route as DashboardSuperadminAuditLogsRouteImport } from './routes/_dashboard/superadmin/audit-logs'
import { Route as DashboardDocsSplatRouteImport } from './routes/_dashboard/docs/$'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUploadsRoute = DashboardUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUnmappedRcRoute = DashboardUnmappedRcRouteImport.update({
  id: '/unmapped-rc',
  path: '/unmapped-rc',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsRoute = DashboardDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDictionaryRoute = DashboardDictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationRoute = DashboardApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuperadminIndexRoute =
  DashboardSuperadminIndexRouteImport.update({
    id: '/superadmin/',
    path: '/superadmin/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocsIndexRoute = DashboardDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDocsRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSuperadminUsersRoute =
  DashboardSuperadminUsersRouteImport.update({
    id: '/superadmin/users',
    path: '/superadmin/users',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuperadminSchedulerRoute =
  DashboardSuperadminSchedulerRouteImport.update({
    id: '/superadmin/scheduler',
    path: '/superadmin/scheduler',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuperadminProcessingRoute =
  DashboardSuperadminProcessingRouteImport.update({
    id: '/superadmin/processing',
    path: '/superadmin/processing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuperadminJobsRoute = DashboardSuperadminJobsRouteImport.update({
  id: '/superadmin/jobs',
  path: '/superadmin/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuperadminHousekeepingRoute =
  DashboardSuperadminHousekeepingRouteImport.update({
    id: '/superadmin/housekeeping',
    path: '/superadmin/housekeeping',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuperadminConfigRoute =
  DashboardSuperadminConfigRouteImport.update({
    id: '/superadmin/config',
    path: '/superadmin/config',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSuperadminAuditLogsRoute =
  DashboardSuperadminAuditLogsRouteImport.update({
    id: '/superadmin/audit-logs',
    path: '/superadmin/audit-logs',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDocsSplatRoute = DashboardDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/application': typeof DashboardApplicationRoute
  '/dictionary': typeof DashboardDictionaryRoute
  '/docs': typeof DashboardDocsRouteWithChildren
  '/transactions': typeof DashboardTransactionsRoute
  '/unmapped-rc': typeof DashboardUnmappedRcRoute
  '/uploads': typeof DashboardUploadsRoute
  '/docs/$': typeof DashboardDocsSplatRoute
  '/superadmin/audit-logs': typeof DashboardSuperadminAuditLogsRoute
  '/superadmin/config': typeof DashboardSuperadminConfigRoute
  '/superadmin/housekeeping': typeof DashboardSuperadminHousekeepingRoute
  '/superadmin/jobs': typeof DashboardSuperadminJobsRoute
  '/superadmin/processing': typeof DashboardSuperadminProcessingRoute
  '/superadmin/scheduler': typeof DashboardSuperadminSchedulerRoute
  '/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/docs/': typeof DashboardDocsIndexRoute
  '/superadmin/': typeof DashboardSuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/application': typeof DashboardApplicationRoute
  '/dictionary': typeof DashboardDictionaryRoute
  '/transactions': typeof DashboardTransactionsRoute
  '/unmapped-rc': typeof DashboardUnmappedRcRoute
  '/uploads': typeof DashboardUploadsRoute
  '/': typeof DashboardIndexRoute
  '/docs/$': typeof DashboardDocsSplatRoute
  '/superadmin/audit-logs': typeof DashboardSuperadminAuditLogsRoute
  '/superadmin/config': typeof DashboardSuperadminConfigRoute
  '/superadmin/housekeeping': typeof DashboardSuperadminHousekeepingRoute
  '/superadmin/jobs': typeof DashboardSuperadminJobsRoute
  '/superadmin/processing': typeof DashboardSuperadminProcessingRoute
  '/superadmin/scheduler': typeof DashboardSuperadminSchedulerRoute
  '/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/docs': typeof DashboardDocsIndexRoute
  '/superadmin': typeof DashboardSuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_dashboard/application': typeof DashboardApplicationRoute
  '/_dashboard/dictionary': typeof DashboardDictionaryRoute
  '/_dashboard/docs': typeof DashboardDocsRouteWithChildren
  '/_dashboard/transactions': typeof DashboardTransactionsRoute
  '/_dashboard/unmapped-rc': typeof DashboardUnmappedRcRoute
  '/_dashboard/uploads': typeof DashboardUploadsRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/docs/$': typeof DashboardDocsSplatRoute
  '/_dashboard/superadmin/audit-logs': typeof DashboardSuperadminAuditLogsRoute
  '/_dashboard/superadmin/config': typeof DashboardSuperadminConfigRoute
  '/_dashboard/superadmin/housekeeping': typeof DashboardSuperadminHousekeepingRoute
  '/_dashboard/superadmin/jobs': typeof DashboardSuperadminJobsRoute
  '/_dashboard/superadmin/processing': typeof DashboardSuperadminProcessingRoute
  '/_dashboard/superadmin/scheduler': typeof DashboardSuperadminSchedulerRoute
  '/_dashboard/superadmin/users': typeof DashboardSuperadminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_dashboard/docs/': typeof DashboardDocsIndexRoute
  '/_dashboard/superadmin/': typeof DashboardSuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/application'
    | '/dictionary'
    | '/docs'
    | '/transactions'
    | '/unmapped-rc'
    | '/uploads'
    | '/docs/$'
    | '/superadmin/audit-logs'
    | '/superadmin/config'
    | '/superadmin/housekeeping'
    | '/superadmin/jobs'
    | '/superadmin/processing'
    | '/superadmin/scheduler'
    | '/superadmin/users'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/docs/'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/application'
    | '/dictionary'
    | '/transactions'
    | '/unmapped-rc'
    | '/uploads'
    | '/'
    | '/docs/$'
    | '/superadmin/audit-logs'
    | '/superadmin/config'
    | '/superadmin/housekeeping'
    | '/superadmin/jobs'
    | '/superadmin/processing'
    | '/superadmin/scheduler'
    | '/superadmin/users'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/docs'
    | '/superadmin'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/register'
    | '/_dashboard/application'
    | '/_dashboard/dictionary'
    | '/_dashboard/docs'
    | '/_dashboard/transactions'
    | '/_dashboard/unmapped-rc'
    | '/_dashboard/uploads'
    | '/_dashboard/'
    | '/_dashboard/docs/$'
    | '/_dashboard/superadmin/audit-logs'
    | '/_dashboard/superadmin/config'
    | '/_dashboard/superadmin/housekeeping'
    | '/_dashboard/superadmin/jobs'
    | '/_dashboard/superadmin/processing'
    | '/_dashboard/superadmin/scheduler'
    | '/_dashboard/superadmin/users'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_dashboard/docs/'
    | '/_dashboard/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/uploads': {
      id: '/_dashboard/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof DashboardUploadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/unmapped-rc': {
      id: '/_dashboard/unmapped-rc'
      path: '/unmapped-rc'
      fullPath: '/unmapped-rc'
      preLoaderRoute: typeof DashboardUnmappedRcRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/transactions': {
      id: '/_dashboard/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs': {
      id: '/_dashboard/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DashboardDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dictionary': {
      id: '/_dashboard/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DashboardDictionaryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/application': {
      id: '/_dashboard/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof DashboardApplicationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/': {
      id: '/_dashboard/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof DashboardSuperadminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/': {
      id: '/_dashboard/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DashboardDocsIndexRouteImport
      parentRoute: typeof DashboardDocsRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/superadmin/users': {
      id: '/_dashboard/superadmin/users'
      path: '/superadmin/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof DashboardSuperadminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/scheduler': {
      id: '/_dashboard/superadmin/scheduler'
      path: '/superadmin/scheduler'
      fullPath: '/superadmin/scheduler'
      preLoaderRoute: typeof DashboardSuperadminSchedulerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/processing': {
      id: '/_dashboard/superadmin/processing'
      path: '/superadmin/processing'
      fullPath: '/superadmin/processing'
      preLoaderRoute: typeof DashboardSuperadminProcessingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/jobs': {
      id: '/_dashboard/superadmin/jobs'
      path: '/superadmin/jobs'
      fullPath: '/superadmin/jobs'
      preLoaderRoute: typeof DashboardSuperadminJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/housekeeping': {
      id: '/_dashboard/superadmin/housekeeping'
      path: '/superadmin/housekeeping'
      fullPath: '/superadmin/housekeeping'
      preLoaderRoute: typeof DashboardSuperadminHousekeepingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/config': {
      id: '/_dashboard/superadmin/config'
      path: '/superadmin/config'
      fullPath: '/superadmin/config'
      preLoaderRoute: typeof DashboardSuperadminConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/superadmin/audit-logs': {
      id: '/_dashboard/superadmin/audit-logs'
      path: '/superadmin/audit-logs'
      fullPath: '/superadmin/audit-logs'
      preLoaderRoute: typeof DashboardSuperadminAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/docs/$': {
      id: '/_dashboard/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DashboardDocsSplatRouteImport
      parentRoute: typeof DashboardDocsRoute
    }
  }
}

interface DashboardDocsRouteChildren {
  DashboardDocsSplatRoute: typeof DashboardDocsSplatRoute
  DashboardDocsIndexRoute: typeof DashboardDocsIndexRoute
}

const DashboardDocsRouteChildren: DashboardDocsRouteChildren = {
  DashboardDocsSplatRoute: DashboardDocsSplatRoute,
  DashboardDocsIndexRoute: DashboardDocsIndexRoute,
}

const DashboardDocsRouteWithChildren = DashboardDocsRoute._addFileChildren(
  DashboardDocsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardApplicationRoute: typeof DashboardApplicationRoute
  DashboardDictionaryRoute: typeof DashboardDictionaryRoute
  DashboardDocsRoute: typeof DashboardDocsRouteWithChildren
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardUnmappedRcRoute: typeof DashboardUnmappedRcRoute
  DashboardUploadsRoute: typeof DashboardUploadsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSuperadminAuditLogsRoute: typeof DashboardSuperadminAuditLogsRoute
  DashboardSuperadminConfigRoute: typeof DashboardSuperadminConfigRoute
  DashboardSuperadminHousekeepingRoute: typeof DashboardSuperadminHousekeepingRoute
  DashboardSuperadminJobsRoute: typeof DashboardSuperadminJobsRoute
  DashboardSuperadminProcessingRoute: typeof DashboardSuperadminProcessingRoute
  DashboardSuperadminSchedulerRoute: typeof DashboardSuperadminSchedulerRoute
  DashboardSuperadminUsersRoute: typeof DashboardSuperadminUsersRoute
  DashboardSuperadminIndexRoute: typeof DashboardSuperadminIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApplicationRoute: DashboardApplicationRoute,
  DashboardDictionaryRoute: DashboardDictionaryRoute,
  DashboardDocsRoute: DashboardDocsRouteWithChildren,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardUnmappedRcRoute: DashboardUnmappedRcRoute,
  DashboardUploadsRoute: DashboardUploadsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSuperadminAuditLogsRoute: DashboardSuperadminAuditLogsRoute,
  DashboardSuperadminConfigRoute: DashboardSuperadminConfigRoute,
  DashboardSuperadminHousekeepingRoute: DashboardSuperadminHousekeepingRoute,
  DashboardSuperadminJobsRoute: DashboardSuperadminJobsRoute,
  DashboardSuperadminProcessingRoute: DashboardSuperadminProcessingRoute,
  DashboardSuperadminSchedulerRoute: DashboardSuperadminSchedulerRoute,
  DashboardSuperadminUsersRoute: DashboardSuperadminUsersRoute,
  DashboardSuperadminIndexRoute: DashboardSuperadminIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
